### ISSUE TITLE
could you add the timbre file for the game "blood"?

### ISSUE THREAD

**Issue by toddfraser88** [Wohlstand/libADLMIDI#1]
I was wondering if could you add the timbre file for the game "blood"? so it's midi's can sound correct?
the original ADLMIDI never added it

I can provide a copy of it for you if you need it

**Comment by Wohlstand** [comment]
Yes,  I can ;-)
How you see I added some extra banks, include hardcoded BuildEngine's bank which can be heard from Sound Setup utility. But it's drums are broken

**Comment by toddfraser88** [comment]
Awesome, thanks!

If you do need a copy of blood's timbre file just let me know

**Comment by Wohlstand** [comment]
Just added three banks ;-)

**Comment by toddfraser88** [comment]
awesome! thanks again!

**Comment by Wohlstand** [comment]
Just sent update to PGE repo https://github.com/Wohlhabend-Networks/PGE-Project/commit/77c91b0bd352c50944cd3c441950e88467f01397
now wait until CIs are will built it (from 15 to 30 minutes)
