### ISSUE TITLE
GZDoom update?

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#113]
This is kind of a toss-up but since you maintain the code I thought I'd ask here.

I think the GZDoom libADLMIDI code is overdue for an update to the new release version, but I would like to have custom voices somehow. If that's not possible, this is the DMXOPL release I made for GZDoom:

https://github.com/sneakernets/DMXOPL/releases/tag/v2.13a

I know this is a lot to ask but this would help me a lot for those who can't compile their own copy of GZDoom from scratch. 

I really appreciate all you've done!

**Comment by Wohlstand** [comment]
I'm already working on an update patch, and also, thanks for a notice I'll take your fresh thing.
GZDoom finally will take ability to switch emulation core on a fly, and I'll try to provide an ability to use custom banks by the same way as FluidSynth's sound fonts are used. But I'll give the flag "Embedded/Custom" to let user choice which one to use.

**Comment by Wohlstand** [comment]
P.S. Just now I have took your fresh release and posted it into master ;3
After small review of one of @jpcima 's branches I'll post the stuff into stable and will apply into GZDoom and that patch is important to toggle more loyal to CPU mode (allow DosBox emulator to don't use native sample rate to load CPU lower when sample rate is lower than native).

**Comment by sneakernets** [comment]
Yay! thank you!

**Comment by Wohlstand** [comment]
Done with one big pull request!
https://github.com/coelckers/gzdoom/pull/511
I did some drafts for external banks loading, but I need to write some other code to look up them. Must not be hard.

**Comment by Wohlstand** [comment]
Good news, @sneakernets , our complete thing has been finally merged! :fox_face: :smile:
