### ISSUE TITLE
Selection of "bend coefficient" value

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#115]
How to fix this piece of code below?
Is this variation of frequency needed, and then should this coefficient receive a dynamic value according to the emulator choice?

https://github.com/Wohlstand/libADLMIDI/blob/6586740caacfb17210a26e9618c31c54ec0da703/src/adlmidi_midiplay.cpp#L1689-L1695

**Comment by Wohlstand** [comment]
Oh! Seems yeah, it's OLD piece of code and it's sensitive to Doom hi-hats, wait I'll check them now, will there are be distorted or not...

**Comment by Wohlstand** [comment]
This is no more needed, I have tested music on 14'th bank, and hi-hats doesn't getting be distorted!
So, everything is fine! :+1:
