### ISSUE TITLE
Add API to get a text description of the channel usage

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#122]
This will be a useful visual debugging tool to observe the channel usage in real time.
It's to elaborate on a feature we have already discussed.

A channel usage string could look like this. (suggestion for one line per chip)
`---+--#-#---@-----`

A symbol may designate several kinds of channel usage:

1. a 2-op channel
2. a (pseudo) 4-op channel
3. a channel which has multiple notes in arpeggio

After such a debugging is made, I would gladly add a panel in adljack to display it.

**Comment by Wohlstand** [comment]
Also, there are rhythm-mode channels may be: it's the "m_channelCategory" array that helps to identify which channel is.

**Comment by jpcima** [comment]
It's done, I close it.
