### ISSUE TITLE
Add the multi-bank map over embedded banks

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#125]
Provide an ability to construct dynamical multi-bank from multiple embedded banks.

The suggested API for that (may be changed if needed):

```c
typedef struct 
{
    /*! Use percussion set, otherwise, melodic set will be used */
    int is_percussion;
    /*! ID of embedded bank to use */
    int embedded_bank_id;
    /*!  MSB MIDI bank number */
    ADL_UInt8  midi_bank_msb;
    /*!  LSB MIDI bank number */
    ADL_UInt8  midi_bank_lsb;
} ADL_BankMapEntry;

/* Constructs the dynamical multi-bank from off the set of embedded banks. 
Returns 0 if everything is fine, otherwise -1 when any error has occurred.
For example, given invalid input data or missing some of required data. */
int adl_setBankMap(struct ADL_MIDIPlayer *device, const ADL_BankMapEntry *bank_map, int bank_map_size);
```

Requested by @kode54

**Comment by jpcima** [comment]
It's a redundant identification of the bank, as there is already the structure `ADL_BankId` to identify.
I can also suggest a function to complete the set of bank API which exist already.

```
ADL_BankId id = [...];

// get/create, and obtain slot iterator
ADL_Bank bank;
adl_getBank(device, &id, ADLMIDI_Bank_Create, &bank);

// load embedded bank into slot
int bankIndex = 0;
adl_loadEmbeddedBank(device, &bank, bankIndex);
```

**Comment by Wohlstand** [comment]
Can this assign different melodic and drumsets from different banks?

**Comment by jpcima** [comment]
Yes: `ADL_BankId` has the `percussion` flag. Depending of this flag, the code can take lower or upper 128 instruments of the embedded bank.

**Comment by Wohlstand** [comment]
Made! Tested, and it works! (I have done the experiment on adlmidiplay side with using of those functions, and result works fine!)
