### ISSUE TITLE
Add LSB bank support for GS behaviour of bank change

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#136]
For now LSB bank number is ignored when GS mode is in use.

Just now, @kode54 have noticed that LSB bank number means the version of instrument on GS synthesizer:
```
1 being SC55, 2 being SC88, 3 SC88 Pro, 4 SC8820
```

So, it's need to make next bank number search algorithm for GS mode:
* When `MSB*256 + LSB` bank was found and have got a non-blank instrument, use it
* When `MSB*256 + LSB` fails or finds blank instrument, use `MSB*256 + 0` as fallback
* When `MSB*256 + 0` also wasn't found or found a blank instrument, then drop to 0'th bank.

**Comment by sneakernets** [comment]
Whoa, do I need to change anything on my bank for this?

**Comment by Wohlstand** [comment]
This doesn't requires you to change anything. But this allow you to create additional banks are will be different by LSB. For example, the base bank is MSB 32 LSB 0. But you can make copy-pasts (and then mod them to fit specified Roland device version) are will have same MSB, but will have LSB 1, 2, 3, 4 in condition to specific Roland device version. If no LSB bank found, the base MSB 32 LSB 0 will be always used as fallback.

**Comment by kode54** [comment]
For instance, at least you can test with SCVA in its different modes, it has different synth bass sounds for SC-55, or for newer versions. Applicable to some games, like the lead instrument in the cyberspace music from System Shock, which sounds different in SC-55 mode compared to the SC-88 and higher modes.

**Comment by Wohlstand** [comment]
As I have tested the stuff, seems, everything is works fine.
@sneakernets , @papiezak , please test GS instrument version for just a case, and if any crap will appear, please report about that issue to let us fix it :fox_face:  :wink:
