### ISSUE TITLE
Playing DMX "doublevoice" patches only play "single voice" on ARM

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#14]
This is odd, but upon loading the latest revision of my DMXOPL bank to generate the adl_data file, playing back my bank only played "half" of the double voice patches. I tested my patch in Doom to see if it was that and, no, that worked... no detune effects, nothing, sounded very flat as a result. Only on ARM does this happen.

Not sure what's going on. on X86 it works just fine...

**Comment by sneakernets** [comment]
Confirmed, it only does it when I generate it. Here is the CPP:

https://gist.github.com/sneakernets/c13b481f79e2a6d0f0f05c03919ac35e

**Comment by Wohlstand** [comment]
Any voice or some?

**Comment by loki666** [comment]
which player are you using to test ?

**Comment by loki666** [comment]
something is wrong in your adldata.cpp

all the ms_sound_koff field are 0

which should affect both arm and x86

**Comment by Wohlstand** [comment]
I have re-downloaded your fresh version of bank and ran generation, and it has been passed, and values are no zeroes (in your adldata.cpp are zeroes). Operating system and compiler which you have used to build gen_adldata?
Everything I doing on Linux x86_64 and GCC  5.4 or GCC 6.2 compilers

**Comment by sneakernets** [comment]
I used clang 5 which had no issues until very recently.

**Comment by sneakernets** [comment]
Maybe I should say this file is from building on the raspberry pi? Because it is.

**Comment by Wohlstand** [comment]
Maybe because of different floating point format or... Endian!
Yeah, ARM has different endian than x86

**Comment by loki666** [comment]
Unlikely... It's probably a compiler bug.

Whatever the hardware / compiler version, they all implement the same
floating point standard (IEEE754). Endianess has nothing to do with that
kind of issue.

**Comment by sneakernets** [comment]
my latest solution is to compile it on my Pentium PC and then copy the file over.

**Comment by Wohlstand** [comment]
Okay, as I see you have found the solution, I can close this. Try out older or newer compiler on same machine where this bug was happen if you can. Also, please try to use any different compiler (such as GCC of any version) and report the result here.

**Comment by sneakernets** [comment]
I will, thanks!

**Comment by Wohlstand** [comment]
Also, yes, floating point is endian dependent: https://stackoverflow.com/questions/2945174/floating-point-endianness

**Comment by Wohlstand** [comment]
Closed due inactivity.
