### ISSUE TITLE
Add DMXOPL v1.11

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#15]
DMXOPLv1.11 is the final OPL2-compatible version.

https://github.com/sneakernets/DMXOPL/releases/tag/v1.11-Final

I'm shifting gears to an OPL3 version that uses all waveforms. It'll take me a while.

This is good news for y'all I guess since v1.11 is the last version. I won't have to badger everyone to update. 😝 

DMXOPL3 will be the next evolution in this, and will be a completely different animal.

**Comment by Wohlstand** [comment]
Be careful, waveforms 0,1,2,3 are work on OPL2, but 4,5,6,7 waveforms is brand new feature of OPL3 and on real OPL2 there are will not work

**Comment by Wohlstand** [comment]
I have been updated this 😉
