### ISSUE TITLE
Add DMXOPL v2.0b (bank 72)

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#16]
My hands hurt. my ears hurt.

https://github.com/sneakernets/DMXOPL/releases/tag/v2.0b

If you could add this so @loki666 can add it to the midi player, That'd be GREAT plzkthx.

**Comment by Wohlstand** [comment]
Tada!
You are lucky, because you have catched me before I gone to sleep 😉

**Comment by sneakernets** [comment]
WOOT!
