### ISSUE TITLE
XMI2MIDI: Are note-offs at end correctly placed inside of this XMI file?

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#160]
I have "DESTRUCT.XMI" file with loop. When loop happens, the note-off doesn't happens. For a test, I have tried to disable event sorter, but the issue is still be. When playing this short theme, on loop edge, one note is still be sustained and wasn't muted. Possible a missing note-off event. This case is needed to be checked... Myself I have checked the sequencer, but it's need to also check the XMI2MIDI. The same XMI is playing fine through XPLAY utility taken from AIL2 package.

[The Lost Vikings - DESTRUCT.zip](https://github.com/Wohlstand/libADLMIDI/files/2328980/The.Lost.Vikings.-.DESTRUCT.zip)

Note: It's not recommended to listen this song without of custom bank because it's not a GM file.

**Comment by jpcima** [comment]
They would seem to be out of the loop's range.
```
    (:delta 0     (note-on 72 :velocity 127 :channel 4))
    (:delta 27    (control #x75 127 :channel 7))
    (:delta 12    (note-on 72 :velocity 0 :channel 2))
    (:delta 0     (note-on 72 :velocity 0 :channel 4))
    (:delta 0     (meta/end)))))
```

The note-off placements of XMI2MID will possibly need some checking.
All of the note-offs events are synthesized, as XMI instead has just note events with durations.

Hypothesis:
Maybe the note events which are current need releasing as a loop branch has been taken?
Maybe it must somewhat restore the key state like it was at the time of entering a loop?

**Comment by Wohlstand** [comment]
I think, it's reasonable to off all notes when reaching a loop end point, let's try that!
As a test, I'll try to make a test MIDI file I'll convert into xmi (via midiform tool) to check the behavior of AIL...
P.S. I did some compassion and I need to extract the AIL volume model as it's a bit different from "generic" we are having...

**Comment by Wohlstand** [comment]
I implemented the workaround: on passing a loop points, the CC123 will be sent to shut up all hanged notes. So, issue had been solved.
