### ISSUE TITLE
adl_metaMarker doesn't properly check pointers

### ISSUE THREAD

**Issue by GabrielRavier** [Wohlstand/libADLMIDI#172]
It uses the device and the play pointer (obtained from calling GET_MIDI_PLAYER with device) without checking for them to be nullptr, and then checks them, which is either useless or a total error

(See adlmidi.cpp, line 911-917)

**Comment by jpcima** [comment]
Thanks for reporting. To add, I think the null checking would need some clean up globally.
In the case of this function, null is unchecked at the entry and has a contradiction, as you have observed.

The implementation has numerous inconsistencies, where it's sometimes both of `device` and `play` checked, only `device`, or no check (example `adl_setBank`).
As we can normalize the way of doing checking, I would think it's the good idea to keep it at one null check, possibly to `assert` the second, considering one can't be not-null without the other.

**Comment by Wohlstand** [comment]
Oh, this is a missing!
Yeah, it's need to check for null both the `device` and `play`... Yeah, assert can be used in `play`.

**Comment by Wohlstand** [comment]
@GabrielRavier , Please review and test the @jpcima 's stuff, I hope it's fine now :fox_face: :wink:

**Comment by GabrielRavier** [comment]
> 
> 
> Closing as this was fixed, but no reply was received from @GabrielRavier to confirm that fix is fine.

I'm bad at looking at my emails 😛

**Comment by GabrielRavier** [comment]
Btw the fix is fine
