### ISSUE TITLE
Add Wolfenstein.OP2?

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#174]
I've noticed Wolfenstein as being missing from adldata.
Do you think this one is worth to add in the collection?

**Comment by Wohlstand** [comment]
It's my old version of "Apogee-IMF-90.wopl", I just forgot to remove it.

**Comment by Wohlstand** [comment]
However, you still can compare it in the bank editor and look at result yourself.

**Comment by jpcima** [comment]
This explanation makes sense :+1: so I'm closing this.
