### ISSUE TITLE
Chip count of 100 with any 4 op Chip count fails in 2018 version

### ISSUE THREAD

**Issue by stgiga** [Wohlstand/libADLMIDI#177]
In droidsound-e, the old library was able to handle a high chip count. The summer 2018 code fails at this high chip count and produces noise at best. It also lags so much that stuff fails to load. Please fix this.

**Comment by Wohlstand** [comment]
That because of Nuked OPL3 emulator which is super-heavy one. Please switch the emulation core into DosBox and retry that.

**Comment by stgiga** [comment]
Dosbox also fails

**Comment by Wohlstand** [comment]
To apply changes of emulator, it's need to stop the song and start it from scratch (in DroidSound-E). Did you that?

Anyway, looks like the author have forgot to pass "Play in PCM rate" flag which does reducing of cycles count and allows to play the song on slower device.

**Comment by Wohlstand** [comment]
By default, DosBox emulator now working under ~49 Khz frequency to match real chip's rate and provide more accurate sound. However, if you are playing in 44100 Khz rate, this means, chip will run with higher rate than the PCM rate. That flag which is exists in the library, forces DosBox chip to run in 44100 Hz rate which makes some distortions in cymbals, hi-hats, etc..

**Comment by Wohlstand** [comment]
This call will set "Lite" mode to run with DosBox emulator with fewer cycles:
https://github.com/Wohlstand/libADLMIDI/blob/master/include/adlmidi.h#L512-L521

**Comment by droidmjt** [comment]
what exactly the "Play in PCM rate" switch do?

**Comment by droidmjt** [comment]
I would like to know how the chip count affects the sound?

**Comment by Wohlstand** [comment]
Look:
* When "Play in PCM rate" is OFF, the DosBox emulator will generate sound in ~49-hz rate that will be resampled into PCM rate. This means, chip itself will run in native rate. In result, each second DosBox will do ~49k cycles per second.
* When "Play in PCM rate" is ON, the DosBox emulator will generate sound in requested sample rate, I.e. it will internally process the logic in given PCM rate. In result, DosBox will do same amount of cycles as PCM rate, e.g. 44100 hz. By default, DosBox did that for a while.

The support for Native rate was introduced to increase sound generation accuracy. For example, you'll hear Hi-Hats, Cymbals, and even some noise-contained melodics will give very different sound than real chip. When you'll run emulator in native rate, the generated sound will be more closed to real chip.

**Comment by Wohlstand** [comment]
> I would like to know how the chip count affects the sound?

Count of chips doesn't affects the sound, but increases the polyphony. Each chip gives 18 2-op voices, OR 6 4-op & 4 2-op voices in dependence on a mode that was set on the chip. Concurrent chips running has introduced to extend the polyphony limit. When music has more parallel voices than available, some other voices will be killed OR the automatic arpeggio will squash chords into one voice.

**Comment by Wohlstand** [comment]
For most of musics the 4~8 or even 16 channels is most approval (I never saw any musics are using thousands of polyphony voices, maybe something surrealistic one that trying to simulate SFX or anything), and running 100 chips looks like some sort of overkill.

**Comment by droidmjt** [comment]
>>For most of musics the 4~8 or even 16 channels is most approval (I never saw any musics are using thousands of polyphony voices, maybe something surrealistic one that trying to simulate SFX or anything), and running 100 chips looks like some sort of overkill.

I agree. So 1-3 chips count should be enough i guess?

**Comment by Wohlstand** [comment]
> I agree. So 1-3 chips count should be enough i guess?

Most of musics are needs 4 chips to be correctly played on 4op banks. But some musics are has more polyphony and there are needs 5 or more chips. I even have an example that overusing chips more than 4 for case of 4op banks. ADLMIDI has many 4op banks.

**Comment by droidmjt** [comment]
1.4GHz mobile device can handle 3 chips, SGS8 can do 6 easily and 6 should be more than enough (used Nuked OPL3 core)

**Comment by Wohlstand** [comment]
My device is able to work with 4 DosBox chips, it's 1.4 Ghz per core.

**Comment by droidmjt** [comment]
Thanks for the infos.

**Comment by droidmjt** [comment]
how many instances you create with adl_init?

**Comment by Wohlstand** [comment]
It's only one adl_init instance is needed. Different `adl_init` instance is means different file player (when you are using libADLMIDI's embedded MIDI sequencer), or second synthesizer with different setup.

**Comment by droidmjt** [comment]
all right, good to know. I tried with DosBox emulator core, 1.4GHz device was able to handle >40 chips, is that normal behaviour?

**Comment by Wohlstand** [comment]
I can't say, as I never tried to load it more than 16 chips, but it's looks good that we now know how much it's able to do :3

**Comment by droidmjt** [comment]
all right :)

**Comment by Wohlstand** [comment]
I think, I'll close this, as the discussion was ended. Any related additional questions still can be asked here.
