### ISSUE TITLE
Optimize initialization of DosBox emulator when using chip native sample rate

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#178]
While Nuked OPL3 does almost instant initialization, DosBox while initialization, does generation of heavy arrays.

It's need to pre-generate them for chip native sample rate, and put them as a separated file. When using this rate, do the silly memcpy of that data rather heavy computing. Use dynamic generation for the case where requested rate doesn't matching chip native.

The function to optimize:
https://github.com/Wohlstand/libADLMIDI/blob/master/src/chips/dosbox/dbopl.cpp#L1297

**Comment by jpcima** [comment]
I don't mind. A generated array makes a smaller binary.
How impacting is this problem on a low performance system?

**Comment by Wohlstand** [comment]
On my phone when I opening any music file and chips are doing initialization, the waiting pause stucks the application. That also happens on powerful systems: in the VLC player a little pause on an attempt to play any song.

**Comment by jpcima** [comment]
Let me propose another thing: cache these tables for the sampling rates used, and share them across instances. Done this way, instantiating the first time will be slow but will be fast next times.

**Comment by Wohlstand** [comment]
Anyway, let's keep one (chip native) as the default state, and when it's need to change sample rate, then, re-generate into something another

**Comment by jpcima** [comment]
You have to consider multi-instances for different sample rates.
I think that the computed data is best kept in a table of tables associated by sample rates, to keep protected by read-write-lock. Native chip rate needn't have a particular case made for it.

**Comment by Wohlstand** [comment]
I may guess, the current one will fail when having multiple instances with different sample rates as tables you can see are static globals.

**Comment by jpcima** [comment]
The initialization should be like this.

```
take the reader's lock;
if (my rate is in map)
   take that table pointer as mine;
else {
  take the writer's lock;
  compute the table for my rate;
  set it as mine;
  insert it in map;
}
```

**Comment by Wohlstand** [comment]
Mission completed!

My Android build of demo app to test yourself:
[ADLMIDI-Player-release.apk.zip](https://github.com/Wohlstand/libADLMIDI/files/2413049/ADLMIDI-Player-release.apk.zip)

(it sucks because it doesn't using foreground service, therefore it can suddenly die in background, and I working on a fix of this - learning foreground services on Android)
