### ISSUE TITLE
Provide pkg-config support

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#186]
Pkg config files are helps various build systems to recognize dependencies and their setup to easier deal with them.

What's need to make:
* adlmidi.pkg.in where CMake is able to pass version number and flags for linking. 
* Let CMake script generate the final file and install it into the system.
* similar for OPNMIDI.

**Comment by jpcima** [comment]
I made the pkg-config. Pushed into this work branch on here.
https://github.com/Wohlstand/libADLMIDI/tree/pkg-config

(tried making a PR, met a temporary error of Github. PR isn't here and it won't let me redo.
Never seen such error before. Probably broken for the time being, hence why doing this)

**Comment by Wohlstand** [comment]
Nice! :3
I'll test this out, and, looks, like I need to make the version to be in one place (for now, it's the part of the public header file).

**Comment by Wohlstand** [comment]
I think, it's fine now,, and no more need to keep this opened. Any further issues will be discussed separately.
