### ISSUE TITLE
use Nuked OPL3 emulator

### ISSUE THREAD

**Issue by loki666** [Wohlstand/libADLMIDI#2]
NukedOPL3 emulator has a very good emulation (close to real OPL3) and is LGPL licensed.
There is a version in adplug (https://github.com/adplug/adplug) which I integrated.
I gave it a quick shot for libADLMIDI, but the result was very bad (crashing sound).

**Comment by Wohlstand** [comment]
I did some experiment with it, but wasn't sent result yet, it seems more accurate, but I still need to optimize something. Also I would have both of them but switch by macro. I need to test it on phones too to be sure it will don't lag on them. (especially SGS III with 1.2 Ghz quad core ARM cpu).
In the Doom banks hi-hats are sounds not fine (especially on libADLMIDI) with Nuked, but mayby some calibration is wrong and again, I think, I'll add it now to have it be switchable via macro.

**Comment by Wohlstand** [comment]
Just small comparison of DOOM hihats generated by DosBox's (current) and by Nuke (register Management still be same):
http://wohlsoft.ru/docs/Music/Misc/drums_hihat_dosbox.ogg
http://wohlsoft.ru/docs/Music/Misc/drums_hihat_nuke.ogg

**Comment by loki666** [comment]
involving @nukeykt
he may have a better opinion on this

**Comment by nukeykt** [comment]
Doom drums are quite frequency sensitive.
172.00093 seems is slightly wrong here:
https://github.com/Wohlstand/libADLMIDI/blob/master/src/adlmidi.cpp#L1209
Try to replace it with 172.4387 and check.

**Comment by Wohlstand** [comment]
@nukeykt , okay, much better:
http://wohlsoft.ru/docs/Music/Misc/drums_hihat_nuke_172.4387.ogg

**Comment by Wohlstand** [comment]
Just pushed everything I made, now I will test this on my phone how it will lag it.
Just for comparison: PGE MusPlayer's CPU load while DosBox's emulator: 0%, Nuked: 12~15% in debug and 2% in release builds.

**Comment by Wohlstand** [comment]
Okay, on phone it lags a lot, and sound is choppy. Seems is really need optimize it for best performance as possible to keep accuracy same

**Comment by loki666** [comment]
I'll give it a try

**Comment by Wohlstand** [comment]
P.S. Why sound is crashing? Which sample rate you are requesting? Also seems you may requested samples incorrectly. It spawns signed 16bit stereo.

**Comment by loki666** [comment]
I just updated my MIDI Player using your changes and it works just fine on my Nexus 5X

https://play.google.com/store/apps/details?id=net.volcanomobile.midiplayer

**Comment by loki666** [comment]
go in the Settings and enable ADLMIDI

**Comment by loki666** [comment]
just tested on a Nexus 4, and indeed, sound is choopy.
maybe you could add a settings to select the emulator at runtime

**Comment by Wohlstand** [comment]
Just installed, waiting until it will fetch all my MIDIs (I have a huge and deep folders tree with lots of MIDIs in my collection), and it still think long time... Ok, just fetched, so long... But work have been done. I have CianogenMod 13 (based on Android 6.0) installed on SGS 3 (latest official for my phone 4.3 is fat, slow and glitchy) (1 GB official vs ~300 MB custom firmware).

I though to make at runtime selection, but some notices I have: ... but, wait, I can have polymorphic class for that to don't change code a lot and just swap pointers while toggling emulator type. Anyway I like Nuked synth, but I don't like it's CPU requirement which I want to fix.

**Comment by Wohlstand** [comment]
Another P.S. Just trying play Corritor 7's IMF files, which by unknown reasons had silent melodic part on DosBox's OPL, but playing fine on Nuked OPL, so, that really makes sense!

**Comment by nukeykt** [comment]
Nuked OPL3 sounds exactly like real OPL3:
https://youtu.be/ftV1XLmLHLE

**Comment by Wohlstand** [comment]
Okay, so, agogo-like snare is not problem and that fine, so, thanks for the proof!

**Comment by Wohlstand** [comment]
Closed because already implemented
