### ISSUE TITLE
add DMXOPL v2.4 (it actually works now!)

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#20]
Thanks to some friends of mine I have made some workarounds for my patch set.

https://github.com/sneakernets/DMXOPL/releases/tag/v2.4-DMX

**Comment by Wohlstand** [comment]
Your bank has been updated!
Sorry for waiting, I was ultra-tired and I had very loaded weeks at my job. But now I'm in action again 😉
