### ISSUE TITLE
Asking for help with Shockolate music

### ISSUE THREAD

**Issue by markkurikola** [Wohlstand/libADLMIDI#202]
I'm not sure if this is the right forum to do this, but here goes; the [Shockolate](https://github.com/Interrupt/systemshock/) source port has been making some nice progress, but one of the things we're struggling with is the way the XMI music sounds a bit "off" because we're defaulting to the SB16 as our way of playing music, as opposed to the General MIDI instruments heard in eg. SSEE. As none of the people involved in the project are experts with these things, we thought it best to ask for help from the experts. 

So, if you'd be kind enough to contribute some of your time and wisdom to the project, we'd really appreciate it.

**Comment by jpcima** [comment]
I don't mind about offering some help to my modest ability.
Then, let's open a discussion of the musical issues at Shockolate side, unless it's strictly a problem or limitation of libADLMIDI's synthesis or sequencer.

For anything about XMI playback, the primary source of information is going to be John Miles's open-source [AIL2](http://www.thegleam.com/ke5fx/misc/AIL2.ZIP) with the provided documentation.

**Comment by Wohlstand** [comment]
I have some tip: if we can't quickly make the correct XMI player, you still have to make it by own, and use libADLMIDI for RealTime mode, e.g. pass MIDI events by yourself, and fetch the audio output in pause periods.

**Comment by markkurikola** [comment]
All right, thanks guys! I'm making [an issue](https://github.com/Interrupt/systemshock/issues/277) on Shockolate, feel free to pitch in.

**Comment by markkurikola** [comment]
Closing this one as we already got a promising PR from jpcima.
