### ISSUE TITLE
User-defined chip profile

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#216]
This idea is to provide a OPL3 core which can be customized by user profiles.

This could serve to establish profiles which are nearer to parcular synthesizer cards:
example "ESS" profile, "Adlib", "Sound blaster [...]", or any custom thing of one's liking.

example:
- editing the wave rom (some cards are reported as having cases of "more distorted" timbre)
- output filter (refer to Dosbox "sblaster" having such a thing)
- have more or less strong low/high notes (key scaling)
- [...]

Some information on the [ESFM](https://lostzap575.weebly.com/blog/archives/02-2018/9)
>#2 ESS ESFM (as found on ESS SOLO-1). ESFM is probably one of the most radically different OPL3 implementations in that it can be subtle. Sometimes it can sound very close to YMF262 (moreso than crystal), but other times, completely different. Because of its use of custom FM instruments under windows, it'll always sound different than YMF262 and CS4236, but there are mixed results in adlib tracker 2. Its major characteristics include slower vibrato, discreet portmanteau, balanced treble/bass, deep toms, and an odd fuzzing distortion on some custom patches.

some current work to enable custom Waves in DOSBox-derived
https://github.com/jpcima/libADLMIDI/tree/chip-profile

**Comment by jpcima** [comment]
This branch allows to experiment custom wave editing
https://github.com/jpcima/OPL3BankEditor/tree/chip-profile

**Comment by Wohlstand** [comment]
Idea seems good, but seems abandoned.
