### ISSUE TITLE
Ability to get samples at native sample rate

### ISSUE THREAD

**Issue by realnc** [Wohlstand/libADLMIDI#217]
It would be useful to be able to get samples at the OPL synth's native sample rate, without any resampling whatsoever performed by libADLMIDI. This way, users of the library can do their own resampling.

My suggestion would be to do this by treating 0 as a special value in `adl_init()`. So `adl_init(0)` would mean that the various generate/play functions (`adl_playFormat()`, `adl_generate()`, etc.) would then generate non-resampled audio samples, basically forwarding the OPL synth's output 1:1 at whatever sample rate the synth generates. A new function would then provide a way to query the native sample rate of each OPL synth. Like:

    int adl_nativeRate(struct ADL_MIDIPlayer *device, ADL_Emulator emulator);

You could instead define these as macros (like `#define ADL_NUKED_RATE 49716`), but a function would be better in case the native rate changes in a future libADLMIDI release and the binary using the library is not recompiled.

**Comment by Wohlstand** [comment]
When you'll set the same native sample rate while initializing, no resampling will be done. I think, yeah, I can give the macro that will contain `49716` constant, maybe `#define ADL_CHIP_NATIVE_RATE 49716` which can be used to easily request the chip native sample rate. For now, all emulators are working in native sample rate until "play at PCM rate" flag will be set which is kept for ability to reduce load on weak devices when using DosBox and similar emulators are able to work in any rate. Nuked is only able work in native rate.

**Comment by realnc** [comment]
Ah! So setting 49716 avoids resampling. Yeah, in that case I guess you can close this bug if you want :-)

**Comment by Wohlstand** [comment]
On a quick hand I have added helper macro and the tip: https://github.com/Wohlstand/libADLMIDI/commit/e62c5354bdd09564a01ec4660ca90baf02e0d7f8 to let figure this out easier for next cases :fox_face: :wink:
