### ISSUE TITLE
Add volume/gain setting functions

### ISSUE THREAD

**Issue by Altazimuth** [Wohlstand/libADLMIDI#22]
The project that I'm implementing libADLMIDI into requires the ability to adjust music volume from inside the program (in this case, solely remaining within the 0-100% range), as the program provides volume sliders.

**Comment by Wohlstand** [comment]
As any audio codec, libADLMIDI doesn't have volume/gain, that yeah. I don't think is a good idea to have own volume/gaining feature in audio codecs (this case a sound generation) library. You can implement that on your sound mixer side. Volume/gain is feature of audio mixer which fetches audio data from codecs, optionally converts them and mixes into united stream which going to audio device.

It's easy super-easy: You have the 16-bit stereo PCM audio chunk buffer generated by libADLMIDI. To have gain, just convert every sample by next formula:
```
sample = int64_t(double(sample) * double(volume));
//volume can have 1.0 -  full volume, between 0.0 and 1.0 - reduced volume. > 1.0 - gaining of volume.
```

So, final example code would look like:
```
//...
short buff[4096];
size_t got = adl_play(myDevice, 4096, buff);

buff_p = buff;
buff_end = buff + got;
double volumeFactor = 1.2; // gain 20%
while(buff_p < buff_end)
{
    *buff_p = short((double)(*buff_p) * volumeFactor);
    buff_p++;
}
//.... Feed your audio output to your audio device!
```

**Comment by Altazimuth** [comment]
That's perfect. Thanks so much!
