### ISSUE TITLE
Install documentation issue

### ISSUE THREAD

**Issue by HunterZ** [Wohlstand/libADLMIDI#238]
In `README.md` it says to specify any desired non-default install location in `CMAKE_PREFIX_PATH`, but this doesn't work.

I tried the standard CMake variable `CMAKE_INSTALL_PREFIX` and it worked fine.

**Comment by Wohlstand** [comment]
That a mistake in document, the CMAKE_PREFIX_PATH is the way to point where are "system" dependencies stored and it's now an install path, gonna fix that when I get my workplace and computer...

**Comment by Wohlstand** [comment]
Thanks for the notice! 🦊👍

**Comment by Wohlstand** [comment]
Done! :fox_face:
