### ISSUE TITLE
adlmidi2: fix ADLMIDI2_VIDEO_OUT_SUPPORT for Windows

### ISSUE THREAD

**Issue by HunterZ** [Wohlstand/libADLMIDI#239]
I noticed that `adlmidi2` has a CMake option `ADLMIDI2_VIDEO_OUT_SUPPORT` that enables support for piping video to `ffmpeg`, but that this isn't supported on Windows because of `popen()`.

Turns out Visual C++ has a compatible implementation named `_popen()`, so I was able to get it working with a few additional minor tweaks: https://twitter.com/HunterZ0/status/1318735497951211521

I will submit a pull request for consideration.

**Comment by Wohlstand** [comment]
Thank you for the fix :fox_face:
