### ISSUE TITLE
GS SC-88Pro drumkits instruments 0-26 and 89-127 are silent

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/libADLMIDI#248]
Happens to libOPNMIDI too (bank will be OPN2 as well, but whatever). 
[gs.tar.gz](https://github.com/Wohlstand/libADLMIDI/files/7172170/gs.tar.gz) - midi and bank

I have a huge problem with percussion instruments beyond 87 (open surdo). The midi in question uses these, but couldn't find them, reporting " - Debug: [10] Playing missing instrument 104" among others. So can add it. It should be in SC-88Pro Standard Set 1 I guess, so I did just that. What happened? Still the same message. The only way to hear these drums is to add them into GM1 Standard drums set, which isn't correct. 

So, am I doing something wrong?

**Comment by Wohlstand** [comment]
What the bank number should be required? I mean include the minor bank number too

**Comment by freq-mod** [comment]
I don't know. SMF-DSP reports MIDI ch11, Acoustic Guitar (steel), so yeah...
I don't know how to check it.

**Comment by freq-mod** [comment]
OH WAIT - I set the bank index LSB to 9, and now it somehow works! That "10" in debug message   Debug: [10] Playing missing instrument 104 misled me - why 10 instead of 9?

**Comment by Wohlstand** [comment]
The base off 0

**Comment by freq-mod** [comment]
oh I see

**Comment by Wohlstand** [comment]
:eyes:

**Comment by freq-mod** [comment]
sorry for bothering, but... somehow it still persists - I forgot to remove instr 104 from GM1 set, but after doing that (and putting it into the correct set, it doesnt play them

**Comment by freq-mod** [comment]
Still I don't know whether drum no. 104 in this midi should be Snare 3 or Phono Noise, it depends from the bank

**Comment by Wohlstand** [comment]
Will need to check some later

**Comment by freq-mod** [comment]
I checked - it must be a Phono Noise and Hip Hop GS drumset. So the problem is with non-GM percussive instruments of indexes 0-27 and 89-127 being silent/not even recognized. MSB doesn't matter it seems :thinking:

**Comment by Wohlstand** [comment]
Closing as abandoned. If really needed something, please give a note.
