### ISSUE TITLE
Implement PCM voice support via emulated SoundBlaster sound source

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/libADLMIDI#249]
I know it's for further future for the same reasons as libOPNMIDI side of things, but such a thing could be possible.

**Comment by Wohlstand** [comment]
HMI and Junglevision literally does this

**Comment by Wohlstand** [comment]
Short demo I made while ago using Junglevision's demo tool
https://user-images.githubusercontent.com/6751442/146235359-f696eb94-9b0d-4ed2-ab49-5a6bc8eb3ac4.mp4

**Comment by freq-mod** [comment]
I know Junglevision has support for FM + PCM, I meant this library
