### ISSUE TITLE
Drum mode still horribly glitchy and broken

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/libADLMIDI#252]
So, I was trying to do OPLL-like bank. OPLL uses drum mode for any kind of percussion. So, if OPL3 has drum mode, it should be okay... but for some reason it's horrifically chaotic. Cymbals and hi-hats change their timbre not song for no reason, can't tune it to anything sensible, drum pitch goes crazy, even with fixed tone note flag....
[opllprealpha.zip](https://github.com/Wohlstand/libADLMIDI/files/7784809/opllprealpha.zip) - file bank anz song showcasing the problem

**Comment by freq-mod** [comment]
@Wohlstand i talked with certain person about rhythm mode operation on OPL chips, and a few questions arose:

-Are rhythm channels triggered via 0xBD, not through the normal note-on registers ?
- Hi-hat and cymbal should use each other's pitches to generate an interference pattern using sth like a ring modulation scheme. Is it taken into consideration?
- snare drum uses the hi-hat multiplier control. Is it taken into consideration?

**Comment by Wohlstand** [comment]
Me here!

- Yes, rhythm-mode channels use 0xBD for note-on/note-off
- Little note that while bass drum, snare and tom has own hertz values, hi-hats and cymbals don't have that, and therefore tom's pitch alts also hihats

**Comment by freq-mod** [comment]
OK, so first aspect is out of the way...  
>bass drum, snare and tom has own hertz values, hi-hats and cymbals don't have that

Pretty sure they all should have hertz values, with caveats described in previous post

**Comment by Wohlstand** [comment]
Closing as abandoned. If something really needed, please re-open and give a note.
