### ISSUE TITLE
Why no ".exe" release?

### ISSUE THREAD

**Issue by paburo-san666** [Wohlstand/libADLMIDI#255]

**Comment by Wohlstand** [comment]
There is a set of binaries built at the https://builds.wohlsoft.ru/win32/, they're is a set of archives with builds of libADLMIDI by various compilers and modes, and there is an executable included too. Also, there is a WinMM driver that allows Windows users to use it by any MIDI player and VLC plugin that allows you to use it in VLC player.

**Comment by paburo-san666** [comment]
Thanks!

**Comment by paburo-san666** [comment]
I couldn't find it, sorry for not looking too much...
