### ISSUE TITLE
Under the dos platform, the 4op sound is not played correctly

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/libADLMIDI#257]
`\music\adlmidi\adlmidi.exe music.mid 58`
If I choose bank number 58, it works perfectly fine, but if I choose bank number 72, the sound is sometimes not right.
`\music\adlmidi\adlmidi.exe music.mid 72`

**Comment by Wohlstand** [comment]
Which music? Can you send me an file you attempted to play? There is a case where 4op banks were limited to using 6 parallel voices only while 2-op channels can use 18 parallel voices.

**Comment by Wohlstand** [comment]
When the music plays more parallel notes than the chip can handle, some of the notes get muted, or (if you enabled an automatic arpeggio), cause notes to be "squished" into a single channel that leads to terrible sounding. You can download the super-latest version where auto-arpeggio behaviour got been disabled by default. So, excited notes will be just muted, not turned into a sounding mess.

**Comment by denjhang** [comment]
It seems to be a problem with the arpeggiator.

https://user-images.githubusercontent.com/61811583/198206984-07da0e41-e909-4be9-9ce8-2168c506c4c9.mp4

**Comment by denjhang** [comment]
[Watery Graves.zip](https://github.com/Wohlstand/libADLMIDI/files/9876346/Watery.Graves.zip)

**Comment by Wohlstand** [comment]
Try this version: https://builds.wohlsoft.ru/dos/adlmidi-dos32.zip

**Comment by denjhang** [comment]
So does libadlmidi support pseudo 4op timbres, and if so, you can have 8 parallel notes (opl3bankeditor told me this fact).

**Comment by Wohlstand** [comment]
Yes, with pseudo-4op voices this works, but, this song actually plays more than 8 parallel notes.

**Comment by denjhang** [comment]
What does CWSDPMI.exe do？

**Comment by Wohlstand** [comment]
CWSDPMI is a ClawseWay (analogue of DOS4GW) dependency, required to run the main program. In DOS, shared libraries were built as EXEs while on Windows they are DLLs.

**Comment by denjhang** [comment]
https://github.com/Wohlstand/libADLMIDI/issues/235
So can I currently use libadlmidi to output vgm? I usually need to use this function on win32 platform.

**Comment by denjhang** [comment]
> Try this version: https://builds.wohlsoft.ru/dos/adlmidi-dos32.zip

Thank you, the problem is initially solved.
