### ISSUE TITLE
Under the DOS platform, it seems that the custom wopl bank cannot be used

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/libADLMIDI#258]
`\music\adl-new\adlmidi.exe  music.mid \music\adl-new\mobv2.wopl`
![sshot-20221027-152930](https://user-images.githubusercontent.com/61811583/198219101-bb906faf-a7f7-4f9a-a6be-b4e71cc6425a.png)
I'm using the example bank from the opl3 bank editor. Every wopl is not correctly identified.

**Comment by Wohlstand** [comment]
Is this path valid? DOS doesn't support 4 letters in filename extensions, so, files will turn into `.WOP`.

**Comment by denjhang** [comment]
![sshot-20221027-153449](https://user-images.githubusercontent.com/61811583/198219941-b7d4b98d-438e-4e53-bbd0-f77da49984d7.png)

**Comment by Wohlstand** [comment]
So, you need to use:
```
\music\adl-new\adlmidi.exe music.mid \music\adl-new\mobv2.wop
```
(the `.WOP` extension, not `.WOPL`)

**Comment by denjhang** [comment]
Suffix names with more than four characters will be forced by DOS with `~1`.

**Comment by Wohlstand** [comment]
So, does this file now works?

**Comment by denjhang** [comment]
It worked, no problem.

**Comment by denjhang** [comment]
mid{    \music\adl-new\adlmidi.exe music.mid -t -v -s \music\adl-new\mobv2~1.WOP }
