### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by yewscion** [Wohlstand/libADLMIDI#259]
The last release, in 2020, has an issue that was resolved in #245 where two of the unit tests fail. It is also 2 years old at this point. Is there any way we could get a new release tag soon, so that packages aren't forced to use arbitrary commits?

**Comment by Wohlstand** [comment]
Good note, I think, I'll make a release tag very soon. Recently I started some XMI work, and I think, I could make a new tag in a few days. the same at the libOPNMIDI side.

**Comment by Wohlstand** [comment]
Okay, I made the 1.5.1 release tag for both libADLMIDI and libOPNMIDI libraries.

**Comment by yewscion** [comment]
Thanks for the quick response!
