### ISSUE TITLE
Demo MIDI player is impossible to compile (at least for me)

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/libADLMIDI#26]
I know that most likely it's not a bug, but I seriously don't know what I am doing wrong.
Trying to make adlmidiplay returns with error:
![adlmidifail](https://user-images.githubusercontent.com/32672779/31781806-ac8aade2-b4f9-11e7-8e81-5ebbc08ba088.PNG)

I am running latest version of MinGW on Windows 7. I have SDL2 installed.

**Comment by Wohlstand** [comment]
It's my fail, SIGHUP is UNIX-only signal and is absence in Windows (no matter MinGW or MSVC environment, but Cygwin has that), I'll fix that

**Comment by Wohlstand** [comment]
If it will fail linking, try to run `make -f Makefile.win32`

**Comment by papiezak** [comment]
OK, now it's better, as it doesn't cry about SIGHUP anymore. But still something is wrong, idk why:
![adlmidifailagain](https://user-images.githubusercontent.com/32672779/31786344-77677bc2-b508-11e7-927f-bf2703a13489.PNG) 
(if it's my fault, sorry about that, I've never truly succeeded in compiling anything in Windows, always relied on Linux and ever so simple sudo make install)

**Comment by Wohlstand** [comment]
Do you have bin folder?
Try `md ..\..\bin` and retry make

**Comment by Wohlstand** [comment]
Or I'll try to debug when I will come to my home

**Comment by Wohlstand** [comment]
Also, to build demo player you must build libADLMIDI itself, seems you wasnt built it as bin folder isn't exist

**Comment by papiezak** [comment]
Thanks for patience :D However:
libadlmidi itself also won't compile! After running "make" it makes two directories: \obj and \-p, then craps out and dies. I would like to provide screen, but it's in my native language rather than English or Russian, so it won"t help ;_; (bin folder was created)

as for adlmidiplay manually creating bin folder doesn't do much

**Comment by Wohlstand** [comment]
Okay, I have tried to build that by myself and it fails too. The reason of this fail because Makefile which is used by default is designed for UNIX, not for Windows. Even Makefile.w32 fails too when I trying to use it manually...
Do you have CMake installed? I gonna to replace current building system with CMake (even an issue for this I have created) which will work much better and will be much more friendly and crossplatform than "crutches" (slang "workaround" in Russian) of manually coded Makefiles

**Comment by Wohlstand** [comment]
In this night I have been added CMake build!
Try to build the project with enabled "WITH_MIDIPLAY" option (that must be easy in the GUI)

**Comment by papiezak** [comment]
OK so installed CMake, downloaded sources, configured and generated build using cmake-gui. It produced a bunch of folders, files, nothing useful. Then I noticed a Makefile, trying to build it:
![adlmidifail3](https://user-images.githubusercontent.com/32672779/31827919-27eb7eb6-b5b9-11e7-9d51-2c5b42186833.PNG)

so still not done yet. or I'm doing sth wrong, which is more plausible lol

**Comment by Wohlstand** [comment]
Disable gen_adldata building, I working on fixing this, it requires C++11, but I don't want enable C++11 flag for everything, for gen_adldata only.

**Comment by papiezak** [comment]
well, that was close, but still compilation fails at the very end: 
![adlmidifail4](https://user-images.githubusercontent.com/32672779/31830242-e507420e-b5bf-11e7-86a3-96998d30c7c9.PNG)

**Comment by Wohlstand** [comment]
You must install libpthread-dev into your MinGW

**Comment by papiezak** [comment]
Well, it has finally compiled!! Thank you SO much!

**Comment by Wohlstand** [comment]
I'm glad to help you, then, I'll close this now :wink:
