### ISSUE TITLE
Sound output compared to OPL3 Bank Editor

### ISSUE THREAD

**Issue by OlPainless** [Wohlstand/libADLMIDI#265]
I'm experimenting with some new sound patches, and I'm having difficulty getting the same sound out of adlmidiplay as in the bank editor. Not sure if there is some additional filtering going on in adlmidiplay which is not present in the bank editor, or something completely different.

Many of the sounds feel a lot thinner in the player, almost as if the first samples are missing/cut off. I'm using the newest master of both projects, using Nuked 1.8 (though it can also be reproduced with dosbox driver). The difference is subtle, but noticeable.

I've created a test .wopl file with one instrument and corresponding test midi file (just a few snare hits), as well as recordings from both bank editor and player. I'm completely open to have missed/messed up something somewhere, and any hints on what are greatly welcomed :)

Kind regards,
Andreas
[sound-differences.zip](https://github.com/Wohlstand/libADLMIDI/files/11313769/sound-differences.zip)

**Comment by Wohlstand** [comment]
What version of bank editor you do use? Please try to take the super-latest code, should be fine. Also, pay attention on:
- what emulator is chosen in the "Settings / emulator"
- what volume level is set (the sould will be slightly different depending on the volume, velocity).

![Снимок экрана от 2023-04-24 22-17-39](https://user-images.githubusercontent.com/6751442/234094561-ba545ae6-1182-452e-afc2-a1985a27df75.png)

Both OPL3-BE and libADLMIDI do use the same volume model and frequency codes even there are different MIDI engines inside (OPL3-BE has a very simplified one when libADLMIDI has a full-features thing).

I checked the thing having both OPL3-BE and libADLMIDI being latest (based on the top of main (`master`) branches of the source code repos), and the result is next:

https://user-images.githubusercontent.com/6751442/234093154-48e0e874-5c72-40f7-aa46-4f4ea7bce44d.mp4

On your example, I heard some junk echo left from previously played instruments.

**Comment by OlPainless** [comment]
Thank you for the detailed test! I think you found the issue, namely the volume: it seems setting it to maximum in the editor will produce the same sound as the player. I'll keep this in mind in the future when making instruments that are sensitive to volume changes.

Once again, thank you for taking the time to make the test and clarify the issue!
