### ISSUE TITLE
how to configure VLC plugin?

### ISSUE THREAD

**Issue by jummy0** [Wohlstand/libADLMIDI#267]
A configuration window is shown [here](https://github.com/Wohlstand/libADLMIDI/issues/38#issuecomment-399929455), but I can't find this window in VLC.

**Comment by jummy0** [comment]
Never mind, I found it. It was locked behind the "advanced settings" checkbox
![image](https://github.com/Wohlstand/libADLMIDI/assets/4022196/cb4624f0-9fb6-4de8-a6bf-8e8bb819f76d)

**Comment by Wohlstand** [comment]
Ye, deep codec setup of any plugin are only appears at "All Settings", and not just mine. :)
