### ISSUE TITLE
Stereo limits

### ISSUE THREAD

**Issue by RushJet1** [Wohlstand/libADLMIDI#268]
Hey, I've been using Libadlmidi for awhile now and was wondering if you could add a user-settable value for when "Full-panning stereo" is not selected.  Currently this just makes many MIDI tracks completely mono, but it would be nice to say if pan is less than 20 away from center, keep it mono, and more than 20, make it stereo.

**Comment by Wohlstand** [comment]
Without the full-panning stereo, OPL3 chip just allows Left, Right and Center. Currently the 32 distance is being used here: https://github.com/Wohlstand/libADLMIDI/blob/master/src/adlmidi_opl3.cpp#L1512C16-L1513
for a while as it's a typical formula for the rest of the stuff. Anyway, if taking a look around, I can see there are other ranges, like, one has 16 distance from the center. At another library I found it also uses 16 distance... Maybe I'll change this distantion too?

**Comment by Wohlstand** [comment]
Done!
Please check the result and tell me, how much it's good now?

**Comment by Wohlstand** [comment]
Closing as no response for a long time.
