### ISSUE TITLE
Descent HMP/HMQ files are completely silent

### ISSUE THREAD

**Issue by NicknineTheEagle** [Wohlstand/libADLMIDI#276]
HMI music files found in Descent play but there's no sound whatsoever. Tried several files from the game and got the same result for each of them. I made sure I picked the right instrument bank for each file. Other games work fine.

**Comment by Wohlstand** [comment]
Hello! Which software you do use to play them? The embedded MIDI sequencer of libADLMIDI doesn't yet support HMI/HMP files. But if you will use the external one, for example, GZDoom's ZMusic library, it should work.

**Comment by NicknineTheEagle** [comment]
Ah, that explains it, I was using adlmidiplay.exe.

**Comment by Wohlstand** [comment]
I guess, there is another issue needed with a task to implement HMI/HMP files support.
