### ISSUE TITLE
Re-implement original ADLMIDI tool by using pure API of libADLMIDI

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#28]
To be ready post everything currently made changes back to original project I need to re-implement same libADLMIDI utility with UI and stuff that catches raw events and visualizes stuff on the screen. Now libADLMIDI has support for hook functions are can be used to catch internal events, data, and messages (to use them for visualizing, debug logging, and any other purposes) and stored meta-tags are can be easily read and printed in any player.

**Comment by Wohlstand** [comment]
Utility has been re-implemented and stored into "utils/adlmidi-2". However, it uses for instrument testing private OPL3 class, part of which must be converted into public API to compensate this private access.

**Comment by Wohlstand** [comment]
Hardware OPL3 is supported now in both simplified demo tool and in Classic ADLMIDI player.

**Comment by papiezak** [comment]
OK, I compiled ADLMIDI2 and I noticed that original tool lags TERRIBLY (at least on Windows, compared to demo MIDI player). Just 3 OPL3 Nuked cores makes most midis unlistenable, whereas demo player starts stuttering when using 7 cores.

**Comment by Wohlstand** [comment]
That because of cluncky console API on Windows side that makes complete work much slower than through bash/tty/xterm on UNIX-like operarimg systems. I think i'll try to add a CMake flag to force that tool use same escape sequencies way that using on unixes to let you try out run a program through Git-Bash (aka, minitty with MSyS thing.

**Comment by Wohlstand** [comment]
P.S. try to turn off reverb by using "-nr" option I have added

**Comment by papiezak** [comment]
OK, now it's better with -nr option (still stutters a little at times).
BTW, will ADLMIDI2 replace demo player in future?

**Comment by Wohlstand** [comment]
No, ADLMIDI2 will serve same role as oroginal ADLMIDI, and purpose of the demo tool is a simplified showcase of libADLMIDI's API and I think, Ill make a second (or many different examples) demo tool which will have nothing except of basic showcase of API calls to explain "how to deal with this library". A current tool is more advanced usage of library and which I use myseld while debug internal of libADMIDI.

**Comment by Wohlstand** [comment]
As everything was made and no issues reported, so, I'll close this.
