### ISSUE TITLE
adl_setLoopEnabled logic is reversed

### ISSUE THREAD

**Issue by loki666** [Wohlstand/libADLMIDI#3]
device->QuitWithoutLooping = (loopEn != 0);
should be 
device->QuitWithoutLooping = (loopEn != 1);

**Comment by Wohlstand** [comment]
Ouch, my fault when I tried to optimize this...
Anyway, I wanted logic "invert (true if not 0)". But seems I just need to set true if "loopEn == 0" Because:
!(loop==1) == (loop == 0)

**Comment by Wohlstand** [comment]
Fixed, Try now

**Comment by loki666** [comment]
seems to works
