### ISSUE TITLE
No sound when using demo midi player

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/libADLMIDI#32]
I don't know what's wrong and since when it's a problem but:
-adlmidiplay.exe builds without any problems, compiler doesn't moan about anything
-it runs without any problems, reads MIDI files, custom banks, etc.. BUT
There's no audio. Nothing can be heard. Sometimes you can hear a very short and quiet click and that's it.

OS is Windows 10 Enterprise, if it helps.

**Comment by Wohlstand** [comment]
Any MIDI file or some of them?
Check out, was libSDL2 built with enabled WASAPI? (find in the SDL config header the define which turns on WASAPI thing).

**Comment by papiezak** [comment]
1. Absulutely all of them
2. I used SDL2 development package for MinGW. It apparently has WASAPI enabled by default.

**Comment by Wohlstand** [comment]
You need to build SDL2 with turned down WASAPI when using Nuked OPL3 emulator. For now is impossible to turn down WASAPI by configure request: https://bugzilla.libsdl.org/show_bug.cgi?id=3798
However, you are can force use DirectSound output from modified code using SDL_OpenAudioDevice(), or set `SDL_AUDIODRIVER` environment variable to `directsound`.

**Comment by papiezak** [comment]
OK, so it's a problem with SDL. I will try my best at hacking config ;_;
BTW building DOSbox emulator produces something... weird.
![dosbox adlmidi demo util](https://user-images.githubusercontent.com/32672779/32980879-c8b50382-cc6e-11e7-9916-cb9ed7541fda.PNG)
that goes on for like 200 lines.

**Comment by Wohlstand** [comment]
Pull update, I have fixed that, MinGW-w64 seems doesn't defines ssize_t while vanilla MinGW does

**Comment by papiezak** [comment]
That's weird, it still craps out:
![dosboxxx](https://user-images.githubusercontent.com/32672779/32981206-b0c4cd02-cc73-11e7-858c-aecdf55965e4.PNG)

**Comment by Wohlstand** [comment]
Okay, let's i'll try to build that by myself... Gonna boot up my Virtual Box VM...

**Comment by Wohlstand** [comment]
Check out again, I tested out that at me and that is now has been fixed!

**Comment by papiezak** [comment]
Yeah, it compiles now!
Too bad thre's no sound... but it's a different thing.

**Comment by Wohlstand** [comment]
Let's I'll check out it with default SDL2 assembly from the site which you have used by yourself to test out for a reason why not works

**Comment by papiezak** [comment]
https://www.libsdl.org/download-2.0.php there it is

**Comment by Wohlstand** [comment]
Okay, I successfully ran Windows 10 on VirtualBox (VMware have dead, and I have tried to use same image on VirtualBox, and it works fine), installed MinGW and CMake, built player, and then I have found that I got the sound when I ran:
```
set SDL_AUDIODRIVER=winmm
```
or
```
set SDL_AUDIODRIVER=directsound
```
And then sound is appears, with Nuked

**Comment by papiezak** [comment]
How to set it? I'm inept at compiling anything on Windows, including SDL.

**Comment by Wohlstand** [comment]
Just type from command line before running player itself, or set it in the system properties as global environment variable `SDL_AUDIODRIVER`

**Comment by papiezak** [comment]
Thanks a lot! Finally I can hear glorious YMF262 audio!

**Comment by Wohlstand** [comment]
Same for YM2612 :wink: (libOPNMIDI project)

**Comment by Wohlstand** [comment]
I'll close this as trouble has been resolved!
