### ISSUE TITLE
IDEA: GZDoom support (need a real-time MIDI event dispatcher)

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#36]
I brought this to the GZDoom devs attention that ADLMidi would be right at home with the other midi options, and I got this response:

> This looks like it very poorly integrates with ZDoom's MIDI code because it cannot use the main event dispatcher but instead wants to do everything on its own.
Find me someone who can make this work within the existing MIDI framework and we should be good to go.

Unfortunately I have no idea what that entails...

GZDoom source is here -> https://github.com/coelckers/gzdoom

**Comment by Wohlstand** [comment]
He means that my library must support real-time playing. I.e. Instead of feeding library by a whole MIDI file, feed it with a chain of events and allow manual tick processing. I have prepared something, but I wasn't finished that stuff yet.

**Comment by Wohlstand** [comment]
Hi!
I just now found the original discussion where you have requested to take the libADLMIDI:
https://forum.zdoom.org/viewtopic.php?f=15&t=58504

I wanted to ask which functions there are would to have to easier take support? I mean functions for real-time event processing.

The easiest way is a function that receives MIDI events in RAW format and does parsing of them internally, or set of functions are reproducing each MIDI event type handing like note on, note off, controller change, etc., and the output function that will generate PCM output from off current state defined by events row sent just now. I.e. inter-event timing you will must to do manually and generate PCM output differently in dependence from delay between events rows. (each "events row" means group of MIDI events are has zero delay between each other).

Harder way which means multi-threading real time:
- generator will generate PCM chunks of same length
- MIDI events will be remembered with a time stamp
- the generated chunk will play all events with calculated delays based on receive timestamps.

First way is good when you playing everything synchronously. Second way is suggested to use when you are receiving MIDI events from real MIDI input device or from another MIDI playing program. I.e. you want use this library as backend of the MIDI playing driver.

**Comment by Wohlstand** [comment]
Okay, in case of FluidSynth I see that there are has the "First way":
https://github.com/videolan/vlc/blob/974e719ba54ecdb2d468048d3ac516020130a831/modules/codec/fluidsynth.c#L262-L301
So, that will go much easier to implement right event dispatching that will don't require you to pass entire MIDI file and pass them independently. Even real-time!

**Comment by Wohlstand** [comment]
P.S. Loops are part of MIDI sequencer that holds all events and iterates them. So, when I will give the real-time event dispatcher (which will do "play everything I just gave now!"), loop will be impossible until MIDI processor on GZDoom side will implement them.

**Comment by sneakernets** [comment]
Oh cool! Glad to see it's possible.

**Comment by Wohlstand** [comment]
I have made some experimental API, which I will try to test as VLC plugin.

**Comment by Wohlstand** [comment]
Okay, I have added API that you are can use:
* Since initialization no more need to open MIDI file to use any generators: just use `adl_generate` to generate chunks between event rows (as you are processing MIDI timing by yourself)
* `adl_rt*` functions to pass MIDI command into the library
* `adl_panic` to shut up all notes
* `adl_rt_resetState` to reset all MIDI controllers into default state

## Usage of library is simple:
* Init by `adl_init()` with giving output sample rate. Output will be always stereo PCM 16-bit little-endian
* Set any properties (bank, deep tremolo / deep vibrato / volume model / count of sound chips)
* While playing, pass any `adl_rt_*` commands and between of them, use `adl_generate` function.

Note: the samples count is absolute, I.e. how much "short"s in a buffer than count of samples in one channel (in case of stereo, you must pass 2x samples count). Return is same - count of array entries.

**Comment by Wohlstand** [comment]
As you can see, I have been registered on the zdoom forum and wrote my annoucement about my changes to let them try to use The Library.

**Comment by sneakernets** [comment]
https://forum.zdoom.org/viewtopic.php?p=1041460#p1041460 Hey sorry for bumping this, but Graf ran into some problems trying to implement it, although his post wasn't very specific on what was going on.

**Comment by Gaerzi** [comment]
If that helps getting more specific, here's the relevant links:

https://github.com/coelckers/gzdoom/commit/7a851fd3f121a8d9fb3923bb0cd156f9dee0b261
https://github.com/coelckers/gzdoom/tree/adlMIDI

**Comment by Wohlstand** [comment]
I have reviewed his code and I have found he was incorrectly requested audio data. I have noticed him that by in-code comment.

-------- Исходное сообщение --------
От: Gaerzi <notifications@github.com> 
Дата:07.03.2018  18:49  (GMT+03:00) 
Кому: Wohlstand/libADLMIDI <libADLMIDI@noreply.github.com> 
Копия: Vitaly Novichkov <admin@wohlnet.ru>,Assign <assign@noreply.github.com> 
Тема: Re: [Wohlstand/libADLMIDI] IDEA: GZDoom support (need a real-time
  MIDI event dispatcher) (#36) 

If that helps getting more specific, here's the relevant links:

coelckers/gzdoom@7a851fd
https://github.com/coelckers/gzdoom/tree/adlMIDI

**Comment by Wohlstand** [comment]
Okay, library has been completely added to GZDoom and now it works fine with an ability to setup some properties. libOPNMIDI also was added into GZDoom.

I think, the task is completely solved. Any future questions will be discussed separately.
