### ISSUE TITLE
Error in function adl_play

### ISSUE THREAD

**Issue by M-HT** [Wohlstand/libADLMIDI#37]
In function adl_play (in file adlmidi.cpp) [there's](https://github.com/Wohlstand/libADLMIDI/blob/8c119d3b710077d67049ee00c9a4ea9b2796623d/src/adlmidi.cpp#L575) this piece of code:
```
if(ate < setup.backup_samples_size)
{
    for(ssize_t j = 0; j < ate; j++)
        setup.backup_samples[(ate - 1) - j] = setup.backup_samples[(setup.backup_samples_size - 1) - j];
}
```
Let's say you have 50 samples in backup buffer and you consumed 10 of them. This code then copies **10** samples from the end of backup buffer to the front of the backup buffer (and backup buffer is shortened to 40 afterwards). This is wrong, because **40** samples should be copied from the end of backup buffer to the front of the backup buffer.

**Comment by Wohlstand** [comment]
Damn! This code piece is really wrong, yeah, good catch! I wanted to do same as you told - copy left samples from end to front, but long time ago when I wrote this, I wrote it incorrectly...

Anyway, I have to get rid of backup buffer (I have a branch for this) and improve MIDI tick accuracy as now every MIDI tick is rounded to 512 samples.

**Comment by Wohlstand** [comment]
Fixed and tested!
Please review this!

**Comment by M-HT** [comment]
Now you're copying **50** samples in my example. You should copy `setup.backup_samples_size - ate` samples.

**Comment by Wohlstand** [comment]
Look carefully:
```cpp
for(ssize_t i = 0, j = ate; j < setup.backup_samples_size; i++, j++)
```
j = ate, I.e. first sample of left buffer.
the iteration is going until end of samples. I.e. the samples at "ate" position will be moved to begin.
Then,
```
setup.backup_samples_size -= ate;
```
which subtracts a size of buffer

**Comment by M-HT** [comment]
You're right, my mistake (I confused `j` with `i`).

**Comment by Wohlstand** [comment]
As this is fixed, I'll close this
