### ISSUE TITLE
Plugin for VLC Media player

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#38]
This plugin must allows to play MIDI files through libADLMIDI by using of VLC Media Player.

The working example is stored in utils/vlc_plugin folder. Buildable on Linux with libvlccore-dev and libvlc-dev packages. Possibly on other platforms which is not tested.

* [x] Fix CMake build (built plugin wont be loaded by VLC. However, same built by autotools-built works fine).
* [x] Add more public codec settings (embedded bank ID, Volume model, Deep-tremolo, deep-vibrato, scaling modulation, etc.)
* [x] Support for both VLC 2.2.2 and latest.
* [x] Test and debug build on Windows platform.
* [x] Make the proper recognizing of codec plugin installation target path (on Linux it's different on Ubuntu 16 and on Ubuntu 18 and not same), and install the compiled SO into that path.
* [ ] Test and debug build on macOS platform.

**Comment by Wohlstand** [comment]
CMake build of VLC plugin has been fixed!
Thanks for the help to `Rémi Denis-Courmont` on VideoLAN forums: https://forum.videolan.org/viewtopic.php?f=2&t=143829

**Comment by papiezak** [comment]
Attempt to build plugin under Windows 7 x64 results in:
![vlc](https://user-images.githubusercontent.com/32672779/38767013-01c50b88-3fdb-11e8-8b07-6860646da7f4.PNG)

Linux Mint works 100% fine.

**Comment by Wohlstand** [comment]
Yeah, I never tested the plugin on Windows, and also, it supports VLC 2.2.2 version only yet, and I will need to add support for latest version by macros.

**Comment by Wohlstand** [comment]
Okay, on the [official forum](https://forum.videolan.org/viewtopic.php?f=2&t=143892&p=471496#p471496) one of developers have pointed me `libvlc_version.h` header which will help me to make a codec be compatible with both legacy and moder versions of VLC. However, for now, I will need to install more fresh VLC build than my in-system to port current stuff into it.

**Comment by papiezak** [comment]
OK WTF: (Ubuntu 18.04 running inside virtualbox)
![vlc](https://user-images.githubusercontent.com/32672779/40271869-1d7c8bfa-5ba4-11e8-8f39-88ac8d563bba.PNG)

**Comment by Wohlstand** [comment]
Which version of VLC? At me was VLC 2.2.2 and the newer VLC has different API I must to support

**Comment by papiezak** [comment]
Aw shiiit, it's 3.0.1 :(

**Comment by Wohlstand** [comment]
At me is built from source VLC 3 I wasn't tested. For now I working on a fix for some, and I'll also try to port to it

**Comment by Wohlstand** [comment]
Just now I have added support for VLC 3!
@papiezak , please pull fresh stuff and try again! :wink:

**Comment by Wohlstand** [comment]
Gotta to backport my changes to OPNMIDI

**Comment by Wohlstand** [comment]
it was built without of UI, but even that it now successfully plays music from a console by my plugins! :wink: 
So, feel free to test arround plugin again, also try to test it on Windows too...

**Comment by papiezak** [comment]
OK, let me check...

- Linux...  builds fine, but I don't remember how to actually install it since it's not a lua extension (I know I'm stupid lol)
- Windows... uh oh 
![vlc win7](https://user-images.githubusercontent.com/32672779/40276476-7f31b192-5c0b-11e8-82fb-30a78c9cf7bb.PNG)
(it's goes on and on )

**Comment by Wohlstand** [comment]
How to install:
Just put the "libadlmidi_plugin.so" (or SymLink to it) into /usr/lib/vlc/plugins/codec/"

About of win build: I'll need to test this out by myself, this still look weird...

**Comment by papiezak** [comment]
On Ubuntu 18.04 (and most likely in an upcoming Linux Mint 19) it goes to /usr/lib/x86_64-linux-gnu/vlc/plugins/codec. That's why I had slight problems

**Comment by papiezak** [comment]
Drums on at least this particular XG midi are broken.
Example: 
[badxg.zip](https://github.com/Wohlstand/libADLMIDI/files/2130571/badxg.zip)

**Comment by papiezak** [comment]
YEAH, sorry my bad, it was a very stupid bug in my DMXOPL mod bank.

**Comment by Wohlstand** [comment]
You right, damn, forgot to add them, gonna to add them on a quick hand...

**Comment by papiezak** [comment]
last time i used windows (a week ago) it wasnt :disappointed:

**Comment by Wohlstand** [comment]
![_2018-06-25_15-10-17](https://user-images.githubusercontent.com/6751442/41849528-f007dce4-7889-11e8-97f9-5c1500f241a6.png)
Now setup is this

**Comment by papiezak** [comment]
aaand here goes nothing:
![vlc win 10](https://user-images.githubusercontent.com/32672779/41850341-6a8eb484-7884-11e8-840b-22d421242f92.PNG)

OK am I doing something wrong?

**Comment by Wohlstand** [comment]
Did you even installed VLC SDK? (or build it from sources)

**Comment by Wohlstand** [comment]
Or maybe need to append more search paths here? https://github.com/Wohlstand/libADLMIDI/blob/ccfb31ab7cd966aeddb106f7a1c3efec6834dccc/cmake/FindLIBVLC.cmake#L35-L44

**Comment by papiezak** [comment]
![vlc take 2](https://user-images.githubusercontent.com/32672779/41851526-745f5bea-7888-11e8-9806-c5548b21a6a1.PNG)

**Comment by papiezak** [comment]
I didn't compile VLC or its SDK from sources. SDK files, devel headers, import libraries come with official 7-zip package.

**Comment by Wohlstand** [comment]
Anyway, try to use MinGW-w64 toolchain instead of vanilla.

**Comment by Wohlstand** [comment]
Seems you are trying to link x86_64 with X86_32, carefully check the archirecture of toolchain and the package (try to use 64-bit MinGW-w64 and 64-bit VLC)

**Comment by papiezak** [comment]
Yeah, getting closer and closer
![vlc take 4](https://user-images.githubusercontent.com/32672779/41897969-0e8ce854-7929-11e8-8b4a-fdd54de263c7.PNG)

**Comment by papiezak** [comment]
To sum up:
CMake produces `objects.a`, which contains `libadlmidi.c.obj` that stops compilation, crying about "undefined references to vlc_module_name". I can't even open it, and `objects.a` is simply not there while building under linux.

**Comment by Wohlstand** [comment]
Okay, just for a test, Try to use autotools build, but before install ADLMIDI library into system first. If it will work, then I have some to change in the build code...

**Comment by Wohlstand** [comment]
It's possibly I need to try review actual pkgconfig on Windows, it's possibly I forgot to link some important libraries...

**Comment by papiezak** [comment]
On Windows I can't get past:
`./configure: line 16932: syntax error near unexpected token 'vlc,'`
`./configure: line 16932: PKG_CHECK_MODULES(vlc, vlc-plugin >= 2.0)'`

vlc sdk installed as previously, I even downloaded `mingw-w64-x86_64-vlc` package, still nothing.
On Linux autotools build works fine.

**Comment by Wohlstand** [comment]
Okay, a bit later I'll give you some test of CMake script you can try out...

**Comment by papiezak** [comment]
Yeah, post it here, I can try out

**Comment by papiezak** [comment]
Looks like  4cf3a53 fixed Windows build, I just compiled OPNMIDI vlc plugin, just I need to check out if it works...

**Comment by papiezak** [comment]
... and looks like it doesn't. Sure, it compiles just fine, but VLC doesn't see/load it when placed in vlc/plugins/codec/

**Comment by Wohlstand** [comment]
What `vlc --list` command is showing?

**Comment by Wohlstand** [comment]
One note: if it's some Windows-specific MIDI plugin to play MIDI files via MIDI-Out, you need to rename it (for example, into `.dll-off`) and restart VLC.

**Comment by papiezak** [comment]
> What vlc --list command is showing?

https://pastebin.com/ys8nbYx3 - there is no mention of any OPN/OPL/MIDI codec, fluidsynth was disabled by me

**Comment by Wohlstand** [comment]
Looks like for Windows I need something different than this:
https://forum.videolan.org/viewtopic.php?f=2&t=143829
to let built plugin be visible by VLC...
Until this thread, Linux build was also invisible to VLC until missing macros was defined...

**Comment by jpcima** [comment]
I don't have the setup to build this but maybe post the compiled dll so I can try analyzing this.

**Comment by Wohlstand** [comment]
Together with built ADLMIDI/OPNMIDI DLL plugin, also please send any random DLL that is working on VLC.

**Comment by Wohlstand** [comment]
So, let's for case of CI deploy the VLC plugins?

**Comment by papiezak** [comment]
_damn i'm ashamed of myself_ 🤦‍♂️ how could I forgot i want to force 64 bit vlc to read 32-bit plugins
interesting, still it's invisible to win32 vlc... i'm lost at this point

**Comment by Wohlstand** [comment]
Then, send 32-bit fluidsynth dll to Pierre for analyze

**Comment by jpcima** [comment]
This has a need for external DLLs. I suppose it will be a solution to force a build as `-static`, and a link with `ADLMIDI_static`.

![capture du 2018-10-09 21-39-10](https://user-images.githubusercontent.com/17614485/46694009-d11f5c00-cc0b-11e8-80a6-62fd19ad27b4.png)

**Comment by Wohlstand** [comment]
Looks, I need to force those modules be built with "-static-libgcc" and "-static-libstdc++" to be fine...
Gonna to make a minor change...

**Comment by jpcima** [comment]
And allow zita-resampler to exist as a static library on my side. Gotta permit that also.

**Comment by Wohlstand** [comment]
For a test, I have posted the some, try to pull that and recompile for a test.

Note: it's possible missing of pthreads, I'll (or Pierre) send the next patch to fix this...

**Comment by papiezak** [comment]
`CMake Error at CMakeLists.txt:540 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "adlmidi_vlc_plugin".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.`

ok...

**Comment by Wohlstand** [comment]
Fixed & sent

**Comment by papiezak** [comment]
Still invisible.

**Comment by papiezak** [comment]
>zita-resampler is sure not to link in this setup, so disable HQ resampler

zita resampler was disabled.

**Comment by jpcima** [comment]
This is now a clean library in very latest commits.

![capture du 2018-10-09 22-53-43](https://user-images.githubusercontent.com/17614485/46697985-36784a80-cc16-11e8-85e6-fdcc38fcedee.png)

**Comment by Wohlstand** [comment]
When @papiezak will confirm the thing works, I'll backport changes to libOPNMIDI

**Comment by papiezak** [comment]
Finally it works now. Thanks a ton!

**Comment by Wohlstand** [comment]
So, the one thing is left - test on macOS!

**Comment by Wohlstand** [comment]
Gonna to backport stuff to libOPNMIDI...

**Comment by papiezak** [comment]
> Please try it on Windows also

Works, , plays .mids, produces sound but looks like (Wohlstand/libOPNMIDI#46) isn't fixed yet, where there isn't any automatic note expanding tweak for very short notes on real-time

**Comment by Wohlstand** [comment]
That a common issue that happens with any RT with no matter: VLC, ADLJack, ADLrt, ADLplug, GZDoom...
When I'll come to my home, I'll try to make the delayed notes thing...

**Comment by Wohlstand** [comment]
For macOS it looks like next:
https://wiki.videolan.org/VLCKit/

**Comment by Wohlstand** [comment]
Just now for a convenience I have made the AppVeyor build that does deployment of VLC plugin for Windows for both 32-bit and 64-bit builds

**Comment by papiezak** [comment]
Noticed that VLC codec lacks some public codec settings such as deep vibrato/tremolo or scalable modulation, so I thought of trying to add it by myself:

https://gist.github.com/papiezak/ffe18123a2a7636a3b68bd5ef5bc3f30

It seems to work, but I don't want to open pull request just yet, since it may be done completely wrong.

**Comment by Wohlstand** [comment]
Be sure that those "deep-tremolo" and "deep-vibrato" are no more boolean: they are tri-state:
* -1 "Auto", means, the state of deep tremolo will be chosen automatically by specs of the bank (for example, AIL banks will turn it on, DMX and TMB banks will turn it off). It's works by default now. I have moved this thing to the WOPL bank side where that is kept per bank.
* 0 "force off" - off deep tremolo with no matter to bank specs.
* 1 "force on" - on deep tremolo with same no matter to bank specs.

The "Adlib percussion mode" flag is near to be completely deprecated as I have to allow per-instrument definition of "rhythm-mode" where each percussion instrument will work on the rhythm-mode channels.

**Comment by papiezak** [comment]
While testing a fix for Wohlstand/libOPNMIDI#46, I noticed some .mids that refuse to play:
`[000055e88bb12790] dummy interface: using the dummy interface module...`
`[00007f0304c17720] smf demux: Track name: `
`[00007f0304c17720] smf demux: Copyright : `
`[00007f0304c17720] smf demux error: fatal parsing error`
`00007f0304c17720] smf demux: Track name: `
`[00007f0304c17720] smf demux: Copyright : `
`[00007f0304c17720] smf demux error: fatal parsing error`

[th08.zip](https://github.com/Wohlstand/libADLMIDI/files/2808988/th08.zip)
The same songs play fine in a command line demo player, and I think, some time ago, they even worked on VLC, but I'm not 100% sure
`

**Comment by Wohlstand** [comment]
Theese errors aren't related to codecs, but VLC-side MIDI parser can't open those MIDIs because of weirdness... Lemme open them in Sekaiju when I'll reach my home and try to tweak around of them...

**Comment by Wohlstand** [comment]
@papiezak, Sekaiju is crashing at me to open any of your MIDI files:
![2019-01-30 01-33-24](https://user-images.githubusercontent.com/6751442/51945206-15d73900-242f-11e9-9887-a47564800214.png)

However, my MIDI sequencer is able to deal with those MIDI files fine... So, I need to inspect those files to find a way to fix them...

**Comment by jpcima** [comment]
Fixed files [th08_fix.zip](https://github.com/Wohlstand/libADLMIDI/files/2810940/th08_fix.zip)
The reason for failure: the meta-event Key-Signature needs 2 bytes of payload, these files have 0.

For VLC, it should be requested to implement permissive parsing to bypass such an error. There are just too numerous MIDI files floating around which don't conform.
Sekaiju needs to implement rigourous bounds checking.

**Comment by Wohlstand** [comment]
@jpcima , @papiezak , good news:
VLC Guys has been fixed this: https://trac.videolan.org/vlc/ticket/21857#comment:3
https://github.com/videolan/vlc/commit/7c50a3589644a64c4fa86b15f663d518ebd9b51d
So, next VLC release would give the result, otherwise, build VLC master branch from source if you wanna get this fixed faster. Or, crazy variant: get the source of your current VLC version, apply this patch to SMF plugin, build VLC and plugins, put the patched plugin into your real VLC installation; must work! :thinking: :fox_face:

**Comment by Wohlstand** [comment]
@jpcima , @papiezak , the fix for MIDI demuxer will appear in VLC 3.0.7: https://forum.videolan.org/viewtopic.php?p=488068#p488068

**Comment by papiezak** [comment]
Yes, and it works fine, as tested on nightly build.
So, the only left to do is check macOS build and maybe review https://gist.github.com/papiezak/ffe18123a2a7636a3b68bd5ef5bc3f30 (added tri-state deep tremolo/vibrato and removed adlib percussion flag)?

**Comment by Wohlstand** [comment]
> (added tri-state deep tremolo/vibrato and removed adlib percussion flag)?
Oh, thanks, I'll check this out at evening...

> check macOS build
Yeah, as I had no any test on macOS yet and I want to make that. The code is compatible, and directly based on FluidSynth plugin taken as a reference for thos.

**Comment by Wohlstand** [comment]
Done a while ago. The macOS side didn't tested yet. That needs a new issue instead of this.
