### ISSUE TITLE
where those values come from ?

### ISSUE THREAD

**Issue by loki666** [Wohlstand/libADLMIDI#39]
https://github.com/Wohlstand/libADLMIDI/blob/9643bd34eb617670b16abd48ae05837fb4a6ef2d/utils/gen_adldata/file_formats/load_wopl.h#L180

the voice2_fine_tune value is very weird
why are there special handling for +1 and -1 and the rest is a linear function ?

from where 0.000025 and -0.000025 are coming from?
BTW: they are so small that they certainly will have no effect on the final value used in the OPL3 register

**Comment by Wohlstand** [comment]
I have calibrated those values experimentally to match sounding on real DMX. That does a small affect and final sound is a bit distorted.

**Comment by loki666** [comment]
it's very weird the special cases for 1 and - 1;

-2 : -0.03125
-1 : -0.000025
0 : 0
1 : +0.000025
2 : +0.03125

so -1, 0, 1 has no effect on the final frequency

It's impossible to measure a frequency variation so small (may be with a laser on the speaker ?)

why isn't it tmp2.voice2_fine_tune = ((fine_tune * 15.625) / 1000.0) for all values of fine_tune ?

**Comment by Wohlstand** [comment]
The result sound will be different from DMX. I added those special cases because sound is different from actual DMX sounding of same voices (look to Tango Accordion and French Horn in Doom banks, please compare with DOS version no matter DosBox or real PC).
