### ISSUE TITLE
adl_play() sometime returns more than requested

### ISSUE THREAD

**Issue by loki666** [Wohlstand/libADLMIDI#4]
int gotten = adl_play(playingDevice, count, data);
gotten is sometimes > count

**Comment by Wohlstand** [comment]
Does that happens on old DosBox-based or that happens now? (after I added Nuked, made few mistakes (and DosBox OPL build crashing in release) which I must fix.). For a test I added assert in my SDL Mixer X's code and just ran debugger and playing various music: nothing happens. Internally I generating set of chunks with ~512 bytes, and non-alligned bytes I storing into backup array which I reusing when data requested again

**Comment by loki666** [comment]
it is happening in both versions.
version at 20aff66 doesnt change adl_play function, so it should not impact this

using this file https://dropfile.to/B2cEDVr

here is my log

AdlMidiPlayer_JNI: ====== start
AdlMidiPlayer_JNI: count = 3544
AdlMidiPlayer_JNI: count = 472
AdlMidiPlayer_JNI: ====== start
AdlMidiPlayer_JNI: count = 3544
AdlMidiPlayer_JNI: ====== start
AdlMidiPlayer_JNI: count = 3544
AdlMidiPlayer_JNI: ====== start
AdlMidiPlayer_JNI: count = 3544
AdlMidiPlayer_JNI: ====== start
AdlMidiPlayer_JNI: count = 3544
AdlMidiPlayer_JNI: count = 82
AdlMidiPlayer_JNI: !!!!! count = 82, gotten = 84


"====== start" is the begining of my function
the first "count = ...." is the total size of my short* buffer, and is used to call adl_play
when there is a secound "count = ....", it's because adl_play returned less than the size I needed. so I call it again.
at the end, you can see that my second call to adl_play request 82 samples, but receive 84 !

**Comment by Wohlstand** [comment]
I played that at me and seems nothing happens. I tried release DosBox's version (just fixed that dumb crash, it happen because uninitializing vector's contents after .resize(), very weird but fixed) and Nuked, both are working fine. Just my example from SDL Mixer X:
(here I also calling SDL's converter to convert sample format into mixer-side (for example, shorts into floats or into chars, into mono, into quadro, etc.) )

```c
/* Play some of a stream previously started with ADLMIDI_play() */
int ADLMIDI_playAudio(struct MUSIC_MIDIADL *music, Uint8 *stream, int len)
{
    if( music==NULL ) return 0;
    if( music->adlmidi == NULL ) return 0;
    if( music->playing == -1 ) return 0;
    if( len < 0 ) return 0;
    int srgArraySize = len * music->cvt.len_mult;
    short* buf = (short*)SDL_malloc((size_t)srgArraySize);
    int srcLen = (int)((double)(len/2.0)/music->cvt.len_ratio);

    int gottenLen = adl_play( music->adlmidi, srcLen, buf );
    if(gottenLen > srcLen)
    {
        printf("OH NOES, THIS HAPPENS!!!!");
        fflush(stdout);
    }
    if( gottenLen <= 0 )
    {
        free(buf);
        return 0;
    }

    int dest_len = gottenLen*2;

    if( music->cvt.needed )
    {
        music->cvt.len = dest_len;
        music->cvt.buf = (Uint8*)buf;
        SDL_ConvertAudio(&music->cvt);
        dest_len = music->cvt.len_cvt;
    }

    if( music->volume == MIX_MAX_VOLUME )
    {
        SDL_memcpy( stream, (Uint8*)buf, (size_t)dest_len );
    } else {
        SDL_MixAudioFormat( stream, (Uint8*)buf, mixer.format, (Uint32)dest_len, music->volume );
    }
    free(buf);
    return len-dest_len;
}
```

**Comment by loki666** [comment]
I'm having difficulties to follow the logic of adl_play() but there are some weird things...

https://github.com/Wohlstand/libADLMIDI/blob/master/src/adlmidi.cpp#L2785
`ssize_t n_samples = 512;ssize_t n_samples_2 = n_samples * 2;`

then
https://github.com/Wohlstand/libADLMIDI/blob/master/src/adlmidi.cpp#L2820
`n_samples = static_cast<ssize_t>(device->carry);`
but you don't recompute n_samples_2, yet you sill use n_samples_2 ( == 1024) to decrement left
https://github.com/Wohlstand/libADLMIDI/blob/master/src/adlmidi.cpp#L2827

I don't know but it seems very weird, 
device->carry seems to depends on eat_delay,
eat_delay is computed with device->delay and device->maxdelay

I'm lost, but I feel there is something going on here, which depending on the buffer size, and maybe compiler and/or midi file input will break

**Comment by Wohlstand** [comment]
I agree that this code is weird, it was made before me, and all generated data was being directly dropped into SDL Audio's queue in original ADLMIDI, but I tried to redesign it to design it as library function.

The function is doing synchronized MIDI event execution (send to registers of all chips a state declared by current tick position on the track) and generating the PCM piece of size equal to time length of one MIDI tick and must fit into requested sample rate.

**Comment by Wohlstand** [comment]
Try now

**Comment by loki666** [comment]
same result

**Comment by Wohlstand** [comment]
And now?

**Comment by loki666** [comment]
seems fixed
thanks

**Comment by Wohlstand** [comment]
P.S. Take latest update again, I just fixed some VERY weird crashes because uninitialized memories (old code)

**Comment by loki666** [comment]
Ok thanks for fixing

**Comment by Wohlstand** [comment]
OOps (you just saw my hotfix I sent now, also take it too)

**Comment by loki666** [comment]
Not using dbopl

**Comment by Wohlstand** [comment]
So, even not using, but ability to use it is important for phones yet (later will add ability use both emulators and switch them in runtime)

**Comment by Wohlstand** [comment]
P.S. which chunk size you are requested? In my PGE MusPlayer I using chunks of 8192, in PGE Editor/Engine 4096

**Comment by loki666** [comment]
3544 on my Nexus 5X. But on another device it might be different.

**Comment by Wohlstand** [comment]
Where you are getting this? In my application I using hardcoded 40960 (experimentally tried to find most optimal to don't have chops in sound stream, but agree if phone can tell that size dynamically):
https://github.com/Wohlstand/ADLMIDI-Player-Java/blob/master/app/src/main/cpp/native-lib.cpp#L46

**Comment by loki666** [comment]
AudioTrack.getMinBufferSize

**Comment by Wohlstand** [comment]
Okay, thanks, will check same on OpenSL ES side or will just pass that value via function call (I tried to use the AudioTrack first time, but to don't overload machine, used OpenSL ES thing)
