### ISSUE TITLE
Some GS instruments aren't playing (wrong banks)

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#40]
Today I was playing that Christmas Song midi that I had made some recordings of, it has an instrument choice on Bank 16 Instrument 24, called "Nylon Gt.o". Unfortunately, libADLMIDI sees it at bank 4096?

![image](https://user-images.githubusercontent.com/5595293/35397755-e39ecd78-01b5-11e8-833c-9945e6ec42cd.png)

![image](https://user-images.githubusercontent.com/5595293/35397769-ec324ac8-01b5-11e8-8578-f184c64c99a6.png)

Is this the midi file or what? It's in SMF0/GS format.

**Comment by sneakernets** [comment]
Here are the MIDI commands to set up that instrument on Channel 4:
![image](https://user-images.githubusercontent.com/5595293/35397954-6fb43546-01b6-11e8-845f-27b5e67d2b95.png)

**Comment by Wohlstand** [comment]
Did you confused MSB or LSB bank codes?

**Comment by sneakernets** [comment]
Hmm, I picked this configuration:
![image](https://user-images.githubusercontent.com/5595293/35398414-6816f052-01b7-11e8-9697-60df8adc15a8.png)

Is this correct? do I need to add something to MSB for this? 🤔

**Comment by sneakernets** [comment]
O---ohhh wait I think I know now. I know with GM2, I need to set MSB to "121" and then the LSB to whatever I need. Is that what I'm missing here? I tried that just now and adlmidi still didn't see my guitar...

**Comment by Wohlstand** [comment]
Bank numbers are parsing by libADLMIDI as unsigned integers, and I think you need to use the calculator to get the binary view of msb/lsb and then convert into decimal. Anyway, I think to solve this inconvenience to give right data format into bank numbers are shown in bank editor's ui to let setup right bank number that will be catched correctly by libADLMIDI's internal. Maybe Ill also provide a test MIDI files for each instrument? I already have a set of test MIDI files for GM set.

**Comment by Wohlstand** [comment]
Try to use bank ID cointing from 0... Instead of from 1... . I had experimenting with TR-808 on linOPNMIDI and I had found that bank ID is different with -1 from standard.

**Comment by papiezak** [comment]
>Try to use bank ID cointing from 0... Instead of from 1... . I had experimenting with TR-808 on linOPNMIDI and I had found that bank ID is different with -1 from standard.

-1? What's on scr below works fine for me 
![tr808](https://user-images.githubusercontent.com/32672779/35509085-198ecff6-04f3-11e8-8cf0-ccadf3696809.PNG)

**Comment by Wohlstand** [comment]
Yeah, I meant when bank ID is 26, the 25 must be set as bank ID in the editor. As data are shown as-is as internally in MIDI files.

**Comment by sneakernets** [comment]
Ah then we're good!
Anyway here's a release: https://github.com/sneakernets/DMXOPL/releases/tag/v2.11e

**Comment by papiezak** [comment]
What about cases like that:
![gs](https://user-images.githubusercontent.com/32672779/39084292-b0fa47ce-4573-11e8-8b51-7ceaff0d8ab6.PNG)

Do I need some specific MSB/LSB values to deal with such crap?

**Comment by Wohlstand** [comment]
I think, I need to look into MIDI file itself, is it valid GS or for something other? For case of GS, MSB is a main bank number when LSB is ignored by GS. Usually if it is 0, then everything must be fine. IF it's GS, but dirty file where are both MSB and LSB used and there are not maching GS bank numbers, that makes misses in full-ranges. As I told before, I must to implement SysEx support to catch GS-Reset event to change the bank number formula. I.e. all LSB values in GS must be zeroed to let foruma be correct.

**Comment by papiezak** [comment]
OK, grab .mid then 
[bls_11t.zip](https://github.com/Wohlstand/libADLMIDI/files/1934532/bls_11t.zip)

**Comment by papiezak** [comment]
It may be an SC-88Pro/SC-8850 midi file.

**Comment by Wohlstand** [comment]
As now SysEx events are implemented, I'm now able to catch "GS Reset" related calls to change behavior of bank changing, so, when GS mode is turned on, LSB part is ignoring, and only MSB is in use. Please test this by yourself.

**Comment by papiezak** [comment]
For me it looks _and sounds_ OK so far.

**Comment by Wohlstand** [comment]
I'll close this as issue has been solved.
