### ISSUE TITLE
Add command-line param for XG brightness control toggle

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#41]
This isn't much of an issue right now, but some XG sequencers initialize the "Brightness" control by default, and set it to some value (this varies though). This is painfully obvious in Yamaha's in-house sequencing work. It totally wrecks some of the voices, so a way to toggle this would be very beneficial.

This usually happens with the Yamaha CVP racks (or any Yamaha rack after 2004) where "Sweet!/Cool!/Natural!/Live!" variants of XG voices exist.

**Comment by Wohlstand** [comment]
The "Brightness" on real XG is just a filter. However it begins to affect voice when it reaches lower than 64 value due specifics of filtering algorithm. At me the Brightness is fully ranged (at 0 to 127) and affects sound at all by changing of level of modulator(s) which results "too-smooth" sound when existing controllers are was targeted to real XG synthesizer (brightness affects between 0 and 64), at me affects at 0 to 127. I would to change that or provide two modes of that (which can be togglable by command line flag / library API call or by SysEx command inside of MIDI file).

**Comment by Wohlstand** [comment]
Good News! :fox:
Just now I made a stuff!
https://github.com/Wohlstand/libADLMIDI/commit/a074c7f2163def562a78ebf4c75e412580dd3118
Feel free to test it! :wink: 
Gotta to port this to libOPNMIDI now!

**Comment by Wohlstand** [comment]
Everything is made!
