### ISSUE TITLE
Implement a callback to receive raw PCM output from every emulated chip

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#45]
To allow developer receive an output of each generated chip individually, provide the callback which will forward output of each emulated chip into specified callback where developer is able to manage PCM data (filter them, or apply effects) to each chip emulator individually.

Planned logic:
* When callback is not set, mix output data directly into output buffer
* When callback is set, write output data of each chip into separated buffers and pass them through of given callback. The mixing into given output buffer will be skipped to allow passing of NULL pointer, however, the size of destination buffer is still be needed.

**Comment by jpcima** [comment]
I think the problem this was about has been resolved, by usage of 32-bit integer mixing.

**Comment by Wohlstand** [comment]
That yeah, and looks this is unneeded thing, as the float32 is a most approval format for any conversions, filtering, etc. if that needed.
