### ISSUE TITLE
The library's version string is incorrect

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#47]
There is currently a problem executing the following code.

```    fprintf(stderr, "ADLMIDI version %s\n", adl_linkedLibraryVersion());```

The output is this. A problem needs to be fixed with the version macros.

```ADLMIDI version OPNMIDI_VERSION_MAJOR.OPNMIDI_VERSION_MINOR.OPNMIDI_VERSION_PATCHLEVEL```

**Comment by Wohlstand** [comment]
I hope, now it's fixed!
