### ISSUE TITLE
CC#120 all sound off not implemented

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#48]
It does not handle this controller. It is supposed to mute a channel's sound output.
In my own fmidi sequencer, I send CC120 to silence the audio when there is a change of track. TiMidity++ recognizes it.

Indeed code reveals it is not a handled cc number. There is however 123, a similar one. (all notes off).
From this, I guess it's probably not a thing on my side to implement, but an omission of ADLMIDI.

cf. MIDIplay::realTime_Controller, adlmidi_midiplay.cpp

**Comment by jpcima** [comment]
This is not right. Playing back a normal midi I can hear nothing except percussions now.
I have pulled your commits into adljack. Until this, I just changed libADLMIDI to make cc120 do the same as 123.

For reference this is how I use the cc120 (which worked with timidity in alsa midi server). [midi_reset](https://github.com/jpcima/fmidi/blob/master/programs/midi-play.cc#L28)
I send this event sequence to reinitialize the instruments between tracks. In reality I don't take this event from the midi files.

**Comment by Wohlstand** [comment]
I have checked the behavior of those events on FluidSynth until I began to implement it. Anyway, can you send me the MIDI file to let me polish my stuff with it?

**Comment by jpcima** [comment]
It's not a problem of one MIDI file, it's a problem of *all* of them.
The only thing is that I work in realtime playback.

Before I pull the last commits => I have sound
After => only percussion

And the stranger thing is, it does not even happen in relation with all sound off events.
On a fresh instance of an ADL player, where cc120 is not sent, the sound channels still start muted.

**Comment by jpcima** [comment]
Here is a picture. Maybe it shows what I mean better.

![screen2](https://user-images.githubusercontent.com/17614485/38530830-157d8f40-3c6d-11e8-9040-76a3d6bbb7d8.png)

**Comment by jpcima** [comment]
Ok here's breaking news. It must have to with the new commits about emulation cores.
Because without these but only the cc120 patch, the sound does play.

**Comment by Wohlstand** [comment]
Anyway, I checked out your adljack, and seems it works unstable, and plays few notes, I ran RtMidi thing I built from sources together with RtAudio. Even I playing MIDI file which has no any CC120 events.

**Comment by Wohlstand** [comment]
P.S. I'll aply CC120 patch to OPNMIDI too as it's confirmed it working right.

**Comment by jpcima** [comment]
> I checked out your adljack, and seems it works unstable

(ah! Maybe I know why, now you mention it. I have to test alsa on motherboard audio, because I'm on a firewire card)

Is the new NukedOPL 1.8 the origin of the sound problems?

**Comment by Wohlstand** [comment]
Oh, yeah, Nuked OPL3 1.8 [had some sounding issue I have been resolved](https://github.com/Wohlstand/libADLMIDI/issues/51)!

**Comment by jpcima** [comment]
I possibly fixed adlrt, please check. The default latency of rtaudio was just set way too low.
I add the flag [-L latency-ms] to choose a latency value. default 20ms

**Comment by Wohlstand** [comment]
I hope, this thing seems useful, Ill try with bigger latency a bit later, for now I gonna sleep and I have powered down my PC.


Отправлено с Samsung Mobile

-------- Исходное сообщение --------
От: JP Cimalando <notifications@github.com> 
Дата:10.04.2018  5:08  (GMT+03:00) 
Кому: Wohlstand/libADLMIDI <libADLMIDI@noreply.github.com> 
Копия: Vitaly Novichkov <admin@wohlnet.ru>,Assign <assign@noreply.github.com> 
Тема: Re: [Wohlstand/libADLMIDI] CC#120 all sound off not implemented (#48) 

I possibly fixed adlrt, please check. The default latency of rtaudio was just set way too low.
I add the flag [-L latency-ms] to choose a latency value. default 20ms

**Comment by jpcima** [comment]
Just for the record so far here's what I know about this sound problem.
If you can run adl-rt, and pull latest libADLMIDI, it's a decent chance you will experience what I speak about.

- the problem has appeared in the timeframe after 0ad695e : from 8a0a939 up to cd09e38
- it does not matter which is the emulator selected. same with Nuked and Dosbox
- it's only in realtime playback. adlmidiplay is OK
- it manifests as if MIDI events are skipped or delayed, but only a few of them pass. It's a best way I can describe this bizarre behavior. It results as if a lot of the music is muted.

**Comment by Wohlstand** [comment]
@jpcima, Okay, just now I figured out for reason why that thing wasn't worked:
https://github.com/Wohlstand/libADLMIDI/commit/ff0982dd98cd7a828730a3498e3e7b9cd1daf868
the mistake was so stupid :man_facepalming: 
OPLChipBase::generate() does replace of content of given buffer, and I needed to use OPLChipBase::generateAndMix() call which mixes a given buffer with new-generated data.

**Comment by jpcima** [comment]
Oh thanks god for finding this!!!! I was going to look into it more after doing some details in the rt player.

**Comment by Wohlstand** [comment]
Okay, as the main topic of this issue resolved, I'll close it. For RTMIDI discussion let's create a new issue :wink:

**Comment by Wohlstand** [comment]
Discussion for RT-MIDI is moved to here: https://github.com/Wohlstand/libADLMIDI/issues/53
