### ISSUE TITLE
Use libc++ on Mac OS

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#61]
Trying to cross-compile for Mac OS on osxcross.
A standard header is not found. It's because in old SDKs of Mac OS the default STL is GCC's. It's not updated by Apple, and old.

It may be a good idea to permit builds with libc++ (or make it default?). Old Mac systems like Snow Leopard don't come with libc++, but Macports allows to acquire it.

```
/home/jpc/Documents/Projects/ADLplug/thirdparty/libADLMIDI/src/adlmidi_private.hpp:90:10: fatal error: 
      'cinttypes' file not found
#include <cinttypes> //PRId32, PRIu32, etc.
```

You can enable libc++ with these CMake lines.

```
if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
endif()
```

EDIT: not the good cmake code, fix

**Comment by Wohlstand** [comment]
You probably can detect the version of macOS / Mac OS X to include different things.

Also, gotta to setup AppVeyor and Travis CI builds to validate build of library on most of platforms.

**Comment by jpcima** [comment]
The selection of libc++ is no big deal in the end, because if I set CMake's C++ flags in the parent project, ADLMIDI will pick it up.
