### ISSUE TITLE
Adlmidiplay leaks memory

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#72]
The memory usage grows when adlmidiplay is left to play on loop for a long time.
A memory leak problem is very likely.

**Comment by Wohlstand** [comment]
Does it happens in old version too or with latest? Anyway, this is serious, I'll check out the thing at home with Valgrind...

**Comment by jpcima** [comment]
I only tried latest.

**Comment by Wohlstand** [comment]
Just for a test, I squished your MIDI file into very-short-length but into one huge tonn of notes, will it cause leak at you?
[true-shit.mid.zip](https://github.com/Wohlstand/libADLMIDI/files/1925964/true-shit.mid.zip)

**Comment by Wohlstand** [comment]
Damn, a conflict when I merging master into `hard-rt`... Gotta to resolve it...

**Comment by Wohlstand** [comment]
Okay, your `hard-rt` even without merging with master (where you made a fix for a `phys` map), it doesn't leaks as I see... However, a question: which version of SDL2 you are using?

**Comment by jpcima** [comment]
Memory usage is going up fast.

![screen](https://user-images.githubusercontent.com/17614485/38964942-10687844-437a-11e8-9e25-e18495c20843.gif)

**Comment by jpcima** [comment]
It's me building with address sanitizer.
:man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: 

It's bizarre why there is no such issue with the rt plugin, which is also built with address sanitizer.
address sanitizer bug maybe?

**Comment by Wohlstand** [comment]
About of SDL  I mean from the `default` branch the freshest state, but yeah, the leak looks very weird... Just for an experiment, try to tweak around of SDL audio driver to turn backend into ALSA or PulseAudio and check the difference in case of memory usage at you, maybe you built with sndio library? I usually disabling it in my build to don't cause dependency hell when running my apps on different distro, or absence of sndio.so will cause a missing so or symbols...

**Comment by Wohlstand** [comment]
Anyway, if the myside crap, try to catch it via valgrind or electric fence...
Okay, seems I sent my reply too late as you just now figured out for a reason and reported here...

**Comment by jpcima** [comment]
@Wohlstand I was building with ASan instrumentations on, and only in this condition it generated the leak.
It's still not entirely normal.

In previous tests, I had LeakSanitizer reports. I could reproduce them each time, but for some reason now I can't get them anymore. I should have saved them.....

The valgrind log is not entirely clean, I'll see if I can find what that is.

**Comment by jpcima** [comment]
The memory which remains at the end is by glibc, for some parts (probably normal)
And the rest from pulseaudio. Is SDL adequately closed at the end?
