### ISSUE TITLE
add DMXOPL

### ISSUE THREAD

**Issue by loki666** [Wohlstand/libADLMIDI#8]
could you include https://github.com/sneakernets/DMXOPL in the patch set ?

**Comment by sneakernets** [comment]
I am okay with this. Please note that it's a constantly moving target, _but_ any releases after 1.7 will be primarily bug fixes

**Comment by Wohlstand** [comment]
Added! ;-)

**Comment by sneakernets** [comment]
Hey, I know this is closed, but I just pushed a big update for this. We're at 1.9.1 now.

**Comment by Wohlstand** [comment]
I'll apply update when I'll reach my job place

**Comment by sneakernets** [comment]
Win! thanks!

**Comment by sneakernets** [comment]
hey @loki666 you there? Just wanted to ping you and let you know he added this. 👍

**Comment by loki666** [comment]
it's included in my MIDI Player v1.6.1

**Comment by sneakernets** [comment]
Yep, another update to this: https://github.com/sneakernets/DMXOPL/releases/tag/v1.10-Final Should be good for a while.
