### ISSUE TITLE
"Warbling sounds" in output

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#9]
This seems to happen on Android, and the Droidsound-E dev was a little fed up with it (https://github.com/droidmjt/Droidsound), it's hard to pin this down. There is a gentle "warble" in the output, as if the pitch slowly drops and rises, like 1 second between "ticks".

I'm not sure where the "bug" is. Could be in ADLMidi, could be in Kode54's midi fork, could be in droidsound. I don't know. But you can definitely hear it! Could this be an Android limitation or resampling error?

**Comment by Wohlstand** [comment]
This is a bug in the sound output code which incorrectly transfers sample buffer generated by libADLMIDI into the audio output interface. That possible when you use "push" strategy and you gave too much audio data to audio output. Once I did that effect when I pushed sound data by HTTP API of a surveillance camera and I gave too much samples, and camera begun to play "warbling music". You must try to try just pass pre-recorded RAW audio through same way and check the result.

**Comment by sneakernets** [comment]
Aha! Nice to know there's a reason. I have a LG G6, which has a pretty fast CPU in it.

**Comment by loki666** [comment]
doest it also happens with my Android MIDI Player ?

**Comment by Wohlstand** [comment]
At me doesn't (SGS III)

**Comment by sneakernets** [comment]
It doesn't happen with your player, no. :)

**Comment by Wohlstand** [comment]
I think, Ill close this as this lose actuality long time ago. Droidsound project has been fixed own issues long times ago.
