### ISSUE TITLE
Some Midi files play at wrong speed

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#91]
Some midi files seem to play at half speed. I have an example midi file attached. the tempo is 120, and ADLMIDI appears to play it at 60.
[Summer In The Park.zip](https://github.com/Wohlstand/libADLMIDI/files/2009427/Summer.In.The.Park.zip)

**Comment by Wohlstand** [comment]
The tempo it takes is 100, and it's because the file itself is sucky and possibly saved by FL Studio. I totally annoyed on it's MIDI files are has wrong offset of tempo event, or the tempo event is storing on some far-far place that is NOT correct for MIDI file...

**Comment by Wohlstand** [comment]
Anyway, I'll review it's internal more detailled, possibly I'll have some workaround to support them. The issue is same to OPNMIDI too

**Comment by Wohlstand** [comment]
While I'm at my job, I can't do anything now, but you can try to compile this editor: https://github.com/Wohlstand/MidiEditor and check out how the tempo event is stored (scroll down in the main window to see non-note events are under the piano). The oldy Sonar 1.2 at me fails to load those damned MIDI files correctly, therefore I fixing them through this MidiEditor to continue the work on them in the Sonar.

**Comment by sneakernets** [comment]
Ah haaaa! I found out what the issue is - in the original MIDI spec, if the tempo wasn't specified, it was assumed to be 120 bpm at 4/4. I didn't know that, as Yamaha always placed tempo markers regardless...

**Comment by Wohlstand** [comment]
Okay, now I can check out the internals of this MIDI file to say why it gives a crap...

![default](https://user-images.githubusercontent.com/6751442/40209996-44151908-5a4b-11e8-9ec0-5eb6a9f39168.png)

The Tempo marker IS in the MIDI file, but... it seems incorrectly aligned and missing up while MIDI data parsing... That case is needed to be checked...

**Comment by Wohlstand** [comment]
Anyway, if it's really default tempo must be 120 than 100, seems it's need to change that to let all tempo-less MIDI files play 120 tempo. Later I'll dump all raw events of MIDI file and check the logic...

**Comment by Wohlstand** [comment]
Just now I have made a small fix, and the thing must work now... Try it out :wink:

**Comment by sneakernets** [comment]
I'll try this now! thanks!

**Comment by sneakernets** [comment]
Yay! it works!
