### ISSUE TITLE
Pitch bender not applied to released notes

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#93]
The pitch bend does no longer apply to notes in release phase after they received note-off.
It contradicts behavior I have in my other synthesizers, so I guess it's anomaly of libADLMIDI.

**Comment by Wohlstand** [comment]
It's normal behavior, even it makes better sound in a case, as example, D_DDTBLU from DOOM 2 where are bells ringing with pitch bend sliding down which results some nice atmospheric sound :smile:

**Comment by Wohlstand** [comment]
Feel free to listen :wink: [D_DDTBLU_fragment.flac.zip](https://github.com/Wohlstand/libADLMIDI/files/2046214/D_DDTBLU_fragment.flac.zip)
(I have recorded it on libOPNMIDI - last that was turned on in my PGE MusPlay I ran to record this showcase)

**Comment by jpcima** [comment]
That's good, but I don't understand. What is special about this music that ordinary pitch bend does not do?
I try to get the doom2 midi files to check how it's done.

I encounter the most helpful help message ever seen :smile: 

```
> deutex --help
Help for DeuTex:
zsh: segmentation fault (core dumped)  deutex --help
```

**Comment by fawtytoo** [comment]
@jpcima If I understand you correctly, pitch bend usually only applies to notes playing. Release phase is after a note off event, therefore pitch bend stops. I believe that's how MIDI instruments behave.

**Comment by Wohlstand** [comment]
Closed as abandoned.
